const pages = [
  {id:'topology',file:'topology.html',name:'底层接入状态雷达拓扑图',icon:'01',section:'capture',sectionName:'业务数据抓取与接入'}
];

const current = document.body.dataset.page || 'topology';
const sections=[...new Map(pages.map(p=>[p.section,p.sectionName])).entries()];
const nav = sections.map(([key,label])=>`<div class="nav-label">${label}</div>${pages.filter(p=>p.section===key).map(p=>`<a class="nav-item ${p.id===current?'active':''}" href="${p.file}"><span class="nav-icon">${p.icon}</span><span>${p.name}</span></a>`).join('')}`).join('');

function stat(label,value,trend,cls=''){return `<div class="stat"><div class="label">${label}</div><div class="value">${value}</div><div class="trend ${cls}">${trend}</div></div>`}
function badge(text,cls='success'){return `<span class="badge ${cls}">${text}</span>`}
function progress(n){return `<div style="display:flex;align-items:center;gap:9px"><div class="progress"><i style="width:${n}%"></i></div><span>${n}%</span></div>`}
function pageHead(title,desc,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
function panel(title,body,tools=''){return `<section class="panel"><div class="panel-head"><h2>${title}</h2><div>${tools}</div></div><div class="panel-body">${body}</div></section>`}

const templates = {
  adapter(){return pageHead('异构数据源接入','统一管理数据库、API与文件类数据源的连接和抽取策略','<button class="btn" data-action="refresh">刷新状态</button><button class="btn primary" data-drawer="source">新增数据源</button>')+
    `<div class="stats">${stat('已接入数据源','28','较上周 +3')}${stat('正常运行','25','可用率 99.6%')}${stat('异常连接','2','需立即处理','danger')}${stat('今日抽取量','1.84 亿','较昨日 +12.4%')}</div>`+
    panel('数据源列表',`<div class="filters"><input class="input" placeholder="搜索数据源名称 / 所属系统"><select class="select"><option>全部类型</option><option>MySQL</option><option>PostgreSQL</option><option>REST API</option></select><select class="select"><option>全部状态</option><option>正常</option><option>异常</option></select><button class="btn" data-action="filter">查询</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>数据源名称</th><th>类型</th><th>所属系统</th><th>抽取方式</th><th>最后同步</th><th>状态</th><th>操作</th></tr></thead><tbody>
    <tr><td><strong>企业主体库</strong><br><span class="muted mono">mysql-prod-01</span></td><td>MySQL 8.0</td><td>科技企业系统</td><td>增量 CDC</td><td>2分钟前</td><td>${badge('正常')}</td><td><a class="text-link" data-drawer="sourceDetail">详情</a><a class="text-link" data-action="test">测试</a></td></tr>
    <tr><td><strong>政策公告接口</strong><br><span class="muted mono">policy-open-api</span></td><td>REST API</td><td>政策服务系统</td><td>每15分钟</td><td>8分钟前</td><td>${badge('正常')}</td><td><a class="text-link" data-drawer="sourceDetail">详情</a><a class="text-link" data-action="test">测试</a></td></tr>
    <tr><td><strong>专利成果库</strong><br><span class="muted mono">patent-pg-02</span></td><td>PostgreSQL</td><td>专利系统</td><td>时间戳增量</td><td>26分钟前</td><td>${badge('延迟','warn')}</td><td><a class="text-link" data-drawer="sourceDetail">详情</a><a class="text-link" data-action="retry">重试</a></td></tr>
    <tr><td><strong>竞品情报源</strong><br><span class="muted mono">competitor-rss</span></td><td>RSS</td><td>情报系统</td><td>每30分钟</td><td>2小时前</td><td>${badge('连接失败','danger')}</td><td><a class="text-link" data-drawer="sourceDetail">详情</a><a class="text-link" data-action="retry">重试</a></td></tr>
    </tbody></table></div>`);},

  hotConfig(){return pageHead('埋点配置动态下发','集中管理各业务系统的事件字段、采样率与版本下发','<button class="btn" data-drawer="history">下发记录</button><button class="btn primary" data-drawer="config">新建配置</button>')+
    `<div class="stats">${stat('在线 SDK','42 / 44','2个实例离线','warn')}${stat('当前配置版本','v3.18.2','今日 10:32 发布')}${stat('下发成功率','97.7%','43个实例已生效')}${stat('待处理回滚','1','专利系统解析失败','danger')}</div>`+
    panel('系统配置概览',`<div class="table-wrap"><table><thead><tr><th>业务系统</th><th>事件数</th><th>采样率</th><th>当前版本</th><th>生效实例</th><th>状态</th><th>操作</th></tr></thead><tbody>
    <tr><td><strong>科技企业系统</strong></td><td>18</td><td>100%</td><td>v3.18.2</td><td>8 / 8</td><td>${badge('已生效')}</td><td><a class="text-link" data-drawer="config">编辑</a><a class="text-link" data-action="publish">重新下发</a></td></tr>
    <tr><td><strong>专利成果系统</strong></td><td>12</td><td>80%</td><td>v3.18.1</td><td>5 / 6</td><td>${badge('部分失败','danger')}</td><td><a class="text-link" data-drawer="config">编辑</a><a class="text-link" data-action="rollback">回滚</a></td></tr>
    <tr><td><strong>政策服务系统</strong></td><td>9</td><td>60%</td><td>v3.17.9</td><td>4 / 4</td><td>${badge('已生效')}</td><td><a class="text-link" data-drawer="config">编辑</a><a class="text-link" data-action="publish">重新下发</a></td></tr>
    <tr><td><strong>情报监测系统</strong></td><td>15</td><td>100%</td><td>v3.18.2</td><td>6 / 6</td><td>${badge('已生效')}</td><td><a class="text-link" data-drawer="config">编辑</a><a class="text-link" data-action="publish">重新下发</a></td></tr>
    </tbody></table></div>`,'<div class="filters"><select class="select"><option>全部系统</option></select><select class="select"><option>全部状态</option></select></div>');},

  schema(){return pageHead('基础表结构变更感知','监测源库 DDL 变更，评估影响并管理字段映射','<button class="btn" data-drawer="watch">监控设置</button><button class="btn primary" data-action="scan">立即扫描</button>')+
    `<div class="stats">${stat('监控实例','12','全部连接正常')}${stat('今日变更','7','新增字段 4 个','warn')}${stat('高风险变更','2','类型变更 / 字段删除','danger')}${stat('已适配','5','自动适配成功率 71.4%')}</div>`+
    panel('变更事件',`<div class="table-wrap"><table><thead><tr><th>发现时间</th><th>数据源 / 表</th><th>变更类型</th><th>变更内容</th><th>影响任务</th><th>处理状态</th><th>操作</th></tr></thead><tbody>
    <tr><td>10:42:18</td><td><strong>企业主体库</strong><br><span class="mono muted">enterprise_info</span></td><td>${badge('字段类型变更','danger')}</td><td><span class="mono">registered_capital</span><br>INT → DECIMAL(18,2)</td><td>3</td><td>${badge('待确认','warn')}</td><td><a class="text-link" data-drawer="diff">查看差异</a></td></tr>
    <tr><td>09:18:02</td><td><strong>政策文件库</strong><br><span class="mono muted">policy_document</span></td><td>${badge('新增字段','info')}</td><td><span class="mono">validity_status VARCHAR(20)</span></td><td>1</td><td>${badge('已自动适配')}</td><td><a class="text-link" data-drawer="diff">查看差异</a></td></tr>
    <tr><td>08:55:31</td><td><strong>专利成果库</strong><br><span class="mono muted">patent_detail</span></td><td>${badge('删除字段','danger')}</td><td><span class="mono">legacy_category</span></td><td>5</td><td>${badge('已拦截','danger')}</td><td><a class="text-link" data-drawer="diff">查看差异</a></td></tr>
    <tr><td>昨日 17:22</td><td><strong>产业指标库</strong><br><span class="mono muted">industry_metric</span></td><td>${badge('新增字段','info')}</td><td><span class="mono">source_level TINYINT</span></td><td>0</td><td>${badge('已处理')}</td><td><a class="text-link" data-drawer="diff">查看差异</a></td></tr>
    </tbody></table></div>`,'<div class="filters"><select class="select"><option>最近7天</option><option>最近30天</option></select><select class="select"><option>全部风险</option></select></div>');},

  apiLimit(){return pageHead('第三方 API 频控保护','管理令牌桶限流、动态配额与熄断降级策略','<button class="btn" data-drawer="limitLog">限流记录</button><button class="btn primary" data-drawer="limit">新建策略</button>')+
    `<div class="stats">${stat('受控 API','18','已启用策略 17 个')}${stat('当前总 QPS','1,286','额度使用 64.3%')}${stat('今日限流','3,842','较昨日 -8.2%')}${stat('熄断中','1','竞品情报 API','danger')}</div>`+
    panel('频控策略',`<div class="table-wrap"><table><thead><tr><th>API名称</th><th>策略类型</th><th>QPS上限</th><th>当前 QPS</th><th>今日限流</th><th>运行状态</th><th>启用</th><th>操作</th></tr></thead><tbody>
    <tr><td><strong>企业工商信息 API</strong><br><span class="mono muted">/v2/enterprise/detail</span></td><td>令牌桶</td><td>500/s</td><td>328/s</td><td>1,204</td><td>${badge('正常')}</td><td><span class="toggle on"></span></td><td><a class="text-link" data-drawer="limit">配置</a></td></tr>
    <tr><td><strong>专利检索 API</strong><br><span class="mono muted">/open/patent/search</span></td><td>滑动窗口</td><td>200/s</td><td>186/s</td><td>2,638</td><td>${badge('高负载','warn')}</td><td><span class="toggle on"></span></td><td><a class="text-link" data-drawer="limit">配置</a></td></tr>
    <tr><td><strong>政策公告 API</strong><br><span class="mono muted">/policy/feed</span></td><td>令牌桶</td><td>100/s</td><td>42/s</td><td>0</td><td>${badge('正常')}</td><td><span class="toggle on"></span></td><td><a class="text-link" data-drawer="limit">配置</a></td></tr>
    <tr><td><strong>竞品情报 API</strong><br><span class="mono muted">/competitor/change</span></td><td>自适应限流</td><td>50/s</td><td>0/s</td><td>--</td><td>${badge('熄断中','danger')}</td><td><span class="toggle on"></span></td><td><a class="text-link" data-drawer="limit">配置</a></td></tr>
    </tbody></table></div>`);},

  consistency(){return pageHead('源系统与中台一致性探针','配置抽样比对任务，跟踪数据一致率与丢失记录','<button class="btn" data-action="export">导出报告</button><button class="btn primary" data-drawer="probe">新建探针</button>')+
    `<div class="stats">${stat('总体一致率','99.84%','较上周 +0.06%')}${stat('今日抽样量','126,800','12个任务已完成')}${stat('字段不一致','183','主要来自企业主体库','warn')}${stat('中台缺失','21','已生成补数任务','danger')}</div>`+
    `<div class="split">${panel('近7日一致率',`<div class="chart">${[96,98,93,97,99,98,100].map((h,i)=>`<div class="bar" style="height:${h}%"><span>${['06/15','06/16','06/17','06/18','06/19','06/20','今日'][i]}</span></div>`).join('')}</div><div style="padding-top:30px" class="muted">整体稳定，6月17日受专利库字段变更影响出现短时波动。</div>`)}${panel('异常分布',`<div class="kpi-line"><span>字段值不一致</span><strong>183</strong></div><div class="kpi-line"><span>源库存在，中台缺失</span><strong class="trend danger">21</strong></div><div class="kpi-line"><span>中台存在，源库缺失</span><strong>8</strong></div><div class="kpi-line"><span>字段映射异常</span><strong>14</strong></div>`)}</div>`+
    panel('最近比对任务',`<div class="table-wrap"><table><thead><tr><th>任务名称</th><th>数据表</th><th>抽样规则</th><th>样本量</th><th>一致率</th><th>状态</th><th>操作</th></tr></thead><tbody><tr><td>企业基本信息日度校验</td><td class="mono">enterprise_info</td><td>随机 2%</td><td>50,000</td><td><strong>99.61%</strong></td><td>${badge('已完成')}</td><td><a class="text-link" data-drawer="probeDetail">查看报告</a></td></tr><tr><td>政策全文完整性校验</td><td class="mono">policy_document</td><td>近24小时全量</td><td>1,248</td><td><strong>100%</strong></td><td>${badge('已完成')}</td><td><a class="text-link" data-drawer="probeDetail">查看报告</a></td></tr><tr><td>专利主数据周期校验</td><td class="mono">patent_detail</td><td>随机 1%</td><td>75,552</td><td><strong>99.93%</strong></td><td>${badge('已完成')}</td><td><a class="text-link" data-drawer="probeDetail">查看报告</a></td></tr></tbody></table></div>`);},

  fullSync(){return pageHead('历史存量数据同步','管理大规模全量迁移任务，支持分片并发、限流与断点续传','<button class="btn" data-action="capacity">容量评估</button><button class="btn primary" data-drawer="sync">新建同步任务</button>')+
    `<div class="stats">${stat('运行中','3','占用 18 个工作线程')}${stat('今日已同步','4.28 亿','平均 62,400 条/秒')}${stat('待处理分片','126','预计 4.6 小时完成')}${stat('失败分片','2','可单独重试','danger')}</div>`+
    panel('同步任务',`<div class="table-wrap"><table><thead><tr><th>任务名称</th><th>源表 → 目标</th><th>数据量</th><th>进度</th><th>当前速度</th><th>状态</th><th>操作</th></tr></thead><tbody>
    <tr><td><strong>企业主体历史数据迁移</strong><br><span class="muted">SYNC-20260621-001</span></td><td><span class="mono">enterprise_info</span><br>→ ODS_ENTERPRISE</td><td>8.2亿</td><td>${progress(68)}</td><td>38,600/s</td><td>${badge('运行中','info')}</td><td><a class="text-link" data-action="pause">暂停</a><a class="text-link" data-drawer="syncDetail">详情</a></td></tr>
    <tr><td><strong>专利全量成果归档</strong><br><span class="muted">SYNC-20260620-008</span></td><td><span class="mono">patent_all</span><br>→ ODS_PATENT</td><td>3.6亿</td><td>${progress(92)}</td><td>21,800/s</td><td>${badge('运行中','info')}</td><td><a class="text-link" data-action="pause">暂停</a><a class="text-link" data-drawer="syncDetail">详情</a></td></tr>
    <tr><td><strong>产业指标历史库</strong><br><span class="muted">SYNC-20260618-016</span></td><td><span class="mono">metric_history</span><br>→ DWD_METRIC</td><td>1.1亿</td><td>${progress(47)}</td><td>--</td><td>${badge('已暂停','warn')}</td><td><a class="text-link" data-action="resumeTask">继续</a><a class="text-link" data-drawer="syncDetail">详情</a></td></tr>
    </tbody></table></div>`);},

  resume(){return pageHead('增量断点续传与防重','监控采集游标、恢复中断任务并处理重复消息','<button class="btn" data-drawer="dedup">防重策略</button><button class="btn primary" data-action="checkAll">全量健康检查</button>')+
    `<div class="stats">${stat('增量任务','16','15个正常运行')}${stat('游标落后','1','专利库落后 26 分钟','warn')}${stat('今日恢复','3','共补齐 286,400 条')}${stat('拦截重复','12,846','防重命中率 0.08%')}</div>`+
    panel('增量任务游标',`<div class="table-wrap"><table><thead><tr><th>任务</th><th>游标类型</th><th>当前游标</th><th>最后持久化</th><th>积压</th><th>防重策略</th><th>状态</th><th>操作</th></tr></thead><tbody>
    <tr><td><strong>企业主体 CDC</strong></td><td>Binlog</td><td class="mono">mysql-bin.018742:894221</td><td>12秒前</td><td>0</td><td>消息ID + 业务主键</td><td>${badge('正常')}</td><td><a class="text-link" data-drawer="cursor">查看游标</a></td></tr>
    <tr><td><strong>专利数据增量</strong></td><td>时间戳</td><td class="mono">2026-06-21 10:18:42</td><td>26分钟前</td><td>48,210</td><td>业务主键</td><td>${badge('游标停滞','warn')}</td><td><a class="text-link" data-action="recover">从断点恢复</a><a class="text-link" data-drawer="cursor">详情</a></td></tr>
    <tr><td><strong>政策事件消费</strong></td><td>Kafka offset</td><td class="mono">p0:884120 / p1:771293</td><td>8秒前</td><td>126</td><td>Bloom Filter</td><td>${badge('正常')}</td><td><a class="text-link" data-drawer="cursor">查看游标</a></td></tr>
    <tr><td><strong>竞品情报抽取</strong></td><td>自增 ID</td><td class="mono">id=18294400</td><td>1分钟前</td><td>18</td><td>消息ID</td><td>${badge('正常')}</td><td><a class="text-link" data-drawer="cursor">查看游标</a></td></tr>
    </tbody></table></div>`);},

  dictionary(){return pageHead('静态枚举与业务字典同步','统一管理部门、行业、地区等维表，审核差异并下发','<button class="btn" data-action="export">导出字典</button><button class="btn primary" data-drawer="dict">新建字典</button>')+
    `<div class="stats">${stat('字典数量','46','覆盖 8 个业务系统')}${stat('字典项','18,426','今日新增 32 项')}${stat('待审核差异','12','删除项 2 个','warn')}${stat('同步成功率','99.7%','近7日平均')}</div>`+
    `<div class="split"><section class="panel"><div class="panel-head"><h2>字典目录</h2><button class="btn small" data-action="syncDict">立即同步</button></div><div class="panel-body"><div class="filters"><input class="input" placeholder="搜索字典名称"></div><div style="margin-top:14px"><div class="kpi-line"><span><strong>组织部门</strong><br><small class="muted">ORG_DEPARTMENT · 328项</small></span>${badge('已同步')}</div><div class="kpi-line"><span><strong>国民经济行业</strong><br><small class="muted">INDUSTRY_CODE · 1,462项</small></span>${badge('3项待审核','warn')}</div><div class="kpi-line"><span><strong>行政区划</strong><br><small class="muted">REGION_CODE · 3,421项</small></span>${badge('已同步')}</div><div class="kpi-line"><span><strong>企业状态</strong><br><small class="muted">ENTERPRISE_STATUS · 16项</small></span>${badge('1项差异','warn')}</div></div></div></section>`+
    panel('字典项：国民经济行业',`<div class="tabs"><span class="tab active">当前版本</span><span class="tab">待审核差异</span><span class="tab">版本记录</span></div><div style="padding-top:14px" class="table-wrap"><table><thead><tr><th>编码</th><th>名称</th><th>上级</th><th>状态</th></tr></thead><tbody><tr><td>A</td><td>农、林、牧、渔业</td><td>--</td><td>${badge('启用')}</td></tr><tr><td>C26</td><td>化学原料和化学制品制造业</td><td>C 制造业</td><td>${badge('启用')}</td></tr><tr><td>I65</td><td>软件和信息技术服务业</td><td>I 信息传输</td><td>${badge('启用')}</td></tr></tbody></table></div><div class="notice" style="margin-top:14px">发现3项源系统差异，需审核后更新中台字典。 <a class="text-link" data-drawer="dictDiff">立即处理</a></div>`)+`</div>`;},

  topology(){return pageHead('底层接入状态雷达拓扑图','展示业务系统数据接入状态，包括异常、延迟、失败次数和责任系统','<button class="btn" data-action="tableMode">切换列表</button><button class="btn primary" data-action="refresh">刷新拓扑</button>')+
    `<div class="stats">${stat('健康节点','6 / 8','总体健康度 92%')}${stat('平均延迟','84 ms','较上小时 -12ms')}${stat('高延迟','1','专利成果系统','warn')}${stat('离线节点','1','竞品情报系统','danger')}</div>`+
    panel('实时接入拓扑',`<div class="legend"><span><i class="dot" style="display:inline-block"></i>健康</span><span><i class="dot warn" style="display:inline-block"></i>延迟</span><span><i class="dot danger" style="display:inline-block"></i>离线</span><span>最后刷新：刚刚</span></div><div class="topology" id="topology"><svg viewBox="0 0 1000 580" preserveAspectRatio="none"><g stroke="#c9d8eb" stroke-width="2">${[[130,105],[500,55],[845,105],[120,300],[855,300],[145,490],[500,520],[840,480]].map(p=>`<line x1="500" y1="255" x2="${p[0]}" y2="${p[1]}"/>`).join('')}</g></svg>
    <div class="node core"><strong>关键数据中台</strong><small>Kafka 集群正常</small></div>
    ${[['科技企业系统','38ms','6%','5%'],['政策服务系统','62ms','43%','3%'],['专利成果系统','428ms','79%','5%','warn'],['科研项目系统','51ms','5%','47%'],['竞品情报系统','无心跳','78%','47%','danger'],['产业指标系统','73ms','8%','82%'],['人才专家系统','95ms','43%','87%'],['科技成果系统','66ms','77%','82%']].map((n,i)=>`<div class="node" data-drawer="node" style="left:${n[2]};top:${n[3]}"><strong><i class="dot ${n[4]||''}"></i>${n[0]}</strong><small>延迟 ${n[1]} · ${n[4]==='danger'?'42秒前':'心跳正常'}</small></div>`).join('')}</div>`,'<div class="filters"><select class="select"><option>实时数据</option><option>近1小时</option></select></div>');}
};



function shell(){
  const p=pages.find(x=>x.id===current);
  return `<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">关</div><div><strong>关键数据更新订阅推送系统</strong><small>DATA SUBSCRIPTION DELIVERY</small></div></div>${nav}<div class="nav-label">AI分析与智能分发</div><a class="nav-item" href="ai-distribution-workbench.html"><span class="nav-icon">02</span><span>复合订阅规则引擎搭建</span></a><div class="nav-label">消息推送与前端展示</div><a class="nav-item" href="message-delivery-workbench.html"><span class="nav-icon">03</span><span>内部工作台站内信与弹窗</span></a></aside><main class="main"><header class="topbar"><div class="crumb">关键数据更新订阅推送系统&nbsp; / &nbsp;${p.sectionName}&nbsp; / &nbsp;<strong>${p.name}</strong></div><div class="top-actions"><div class="search-mini">搜索功能、数据源...</div><span>帮助</span><span>通知 <b style="color:#e65252">3</b></span><div class="avatar">管</div><span>系统管理员</span></div></header><div class="content">${templates[current]()}</div></main></div><div class="drawer-backdrop" id="drawer"><aside class="drawer"><div class="drawer-head"><strong id="drawerTitle">详情</strong><button class="close" data-close>&times;</button></div><div id="drawerBody"></div></aside></div><div class="toast" id="toast"></div>`;
}

document.getElementById('app').innerHTML=shell();

const drawerContent={
 source:['新增数据源',`<div class="form-grid"><div class="field full"><label>数据源名称 *</label><input class="input" value="科研项目库"></div><div class="field"><label>数据源类型 *</label><select class="select"><option>MySQL</option><option>PostgreSQL</option><option>REST API</option><option>Kafka</option></select></div><div class="field"><label>所属业务系统</label><select class="select"><option>科研项目系统</option></select></div><div class="field full"><label>JDBC URL *</label><input class="input mono" value="jdbc:mysql://10.20.16.8:3306/research"></div><div class="field"><label>用户名</label><input class="input" value="data_reader"></div><div class="field"><label>密码</label><input class="input" type="password" value="12345678"></div><div class="field"><label>抽取方式</label><select class="select"><option>增量 CDC</option><option>定时全量</option><option>时间戳增量</option></select></div><div class="field"><label>执行周期</label><select class="select"><option>实时</option><option>每5分钟</option></select></div></div><div class="notice" style="margin-top:18px">连接信息将加密保存，仅数据接入服务可解密使用。</div><div class="drawer-foot"><button class="btn" data-action="test">测试连接</button><button class="btn primary" data-save>保存并启用</button></div>`],
 sourceDetail:['数据源详情',`<div class="notice">连接正常，最近1小时无错误。</div><div class="kpi-line"><span>连接地址</span><strong class="mono">10.20.16.8:3306</strong></div><div class="kpi-line"><span>平均延迟</span><strong>38 ms</strong></div><div class="kpi-line"><span>今日抽取</span><strong>6,284万条</strong></div><div class="kpi-line"><span>异常重试</span><strong>0次</strong></div><h3>运行记录</h3><div class="timeline"><div class="timeline-item"><strong>增量抽取完成</strong><span class="muted">10:42 · 125,820条</span></div><div class="timeline-item"><strong>健康检查通过</strong><span class="muted">10:40 · 延迟38ms</span></div></div>`],
 config:['埋点配置',`<div class="form-grid"><div class="field full"><label>业务系统</label><select class="select"><option>科技企业系统</option></select></div><div class="field"><label>事件名称</label><input class="input" value="enterprise.updated"></div><div class="field"><label>采样率</label><input class="input" value="100%"></div><div class="field full"><label>关键字段</label><div class="codebox">enterprise_id : string  // 必填<br>changed_fields : array<br>operator_id : string<br>occurred_at : datetime</div></div><div class="field"><label>发布方式</label><select class="select"><option>灰度发布 20%</option><option>全量发布</option></select></div><div class="field"><label>失败策略</label><select class="select"><option>自动回滚</option><option>保持原配置</option></select></div></div><div class="drawer-foot"><button class="btn" data-close>取消</button><button class="btn primary" data-action="publish">发布配置</button></div>`],
 history:['配置下发记录',`<div class="timeline"><div class="timeline-item"><strong>v3.18.2 全量发布</strong><span class="muted">今日 10:32 · 管理员 · 43/44成功</span></div><div class="timeline-item"><strong>v3.18.1 灰度发布</strong><span class="muted">昨日 16:18 · 王工 · 10/10成功</span></div><div class="timeline-item"><strong>v3.17.9 全量发布</strong><span class="muted">06-19 14:06 · 张工 · 42/42成功</span></div></div>`],
 diff:['表结构变更详情',`<div class="notice">高风险：字段类型变更将影响3个下游任务。</div><h3>变更对比</h3><div class="split"><div><small class="muted">变更前</small><div class="codebox">registered_capital INT NOT NULL</div></div><div><small class="muted">变更后</small><div class="codebox">registered_capital DECIMAL(18,2) NOT NULL</div></div></div><h3>影响范围</h3><div class="kpi-line"><span>enterprise_cdc_ingest</span>${badge('需更新映射','warn')}</div><div class="kpi-line"><span>enterprise_profile_build</span>${badge('兼容')}</div><div class="kpi-line"><span>capital_change_alert</span>${badge('需回归','warn')}</div><div class="drawer-foot"><button class="btn danger" data-action="ignore">忽略变更</button><button class="btn primary" data-save>确认并更新映射</button></div>`],
 watch:['监控设置',`<div class="form-grid"><div class="field full"><label>监控数据库</label><select class="select"><option>全部生产数据库</option></select></div><div class="field"><label>检测周期</label><select class="select"><option>每5分钟</option></select></div><div class="field"><label>自动适配</label><select class="select"><option>仅新增字段</option></select></div><div class="field full"><label>告警通知</label><input class="input" value="运维告警群、data-admin@example.com"></div></div><div class="drawer-foot"><button class="btn primary" data-save>保存设置</button></div>`],
 limit:['API频控策略',`<div class="form-grid"><div class="field full"><label>API名称</label><input class="input" value="企业工商信息 API"></div><div class="field"><label>算法</label><select class="select"><option>令牌桶</option><option>滑动窗口</option></select></div><div class="field"><label>QPS上限</label><input class="input" value="500"></div><div class="field"><label>桶容量</label><input class="input" value="1000"></div><div class="field"><label>超限处理</label><select class="select"><option>排队等待</option><option>直接拒绝</option></select></div><div class="field"><label>连续失败阈值</label><input class="input" value="5次"></div><div class="field"><label>熄断时长</label><input class="input" value="60秒"></div></div><div class="notice" style="margin-top:18px">将根据第三方响应头中的剩余配额自动调整发送速率。</div><div class="drawer-foot"><button class="btn primary" data-save>保存并生效</button></div>`],
 limitLog:['限流记录',`<div class="timeline"><div class="timeline-item"><strong>专利检索 API 触发排队</strong><span class="muted">10:42:11 · QPS 208 / 阈值 200</span></div><div class="timeline-item"><strong>竞品情报 API 触发熄断</strong><span class="muted">10:18:25 · 连续5次返回429</span></div></div>`],
 probe:['新建一致性探针',`<div class="form-grid"><div class="field full"><label>任务名称</label><input class="input" value="企业基本信息日度校验"></div><div class="field"><label>源表</label><select class="select"><option>enterprise_info</option></select></div><div class="field"><label>中台表</label><select class="select"><option>ODS_ENTERPRISE_INFO</option></select></div><div class="field"><label>抽样比例</label><input class="input" value="2%"></div><div class="field"><label>执行周期</label><select class="select"><option>每日 02:00</option></select></div><div class="field full"><label>比对字段</label><input class="input" value="name, credit_code, registered_capital, status"></div></div><div class="drawer-foot"><button class="btn primary" data-save>创建并执行</button></div>`],
 probeDetail:['一致性报告',`<div class="stats" style="grid-template-columns:1fr 1fr"><div class="stat"><div class="label">一致率</div><div class="value">99.61%</div></div><div class="stat"><div class="label">异常记录</div><div class="value">195</div></div></div><h3>异常样例</h3><div class="codebox">UID: E10288429<br>field: registered_capital<br>source: 5000000<br>platform: 500000</div><div class="drawer-foot"><button class="btn" data-action="export">导出异常明细</button><button class="btn primary" data-action="repair">生成补数任务</button></div>`],
 sync:['新建全量同步任务',`<div class="form-grid"><div class="field full"><label>任务名称</label><input class="input" value="科研项目历史数据迁移"></div><div class="field"><label>源表</label><select class="select"><option>research_project</option></select></div><div class="field"><label>目标表</label><select class="select"><option>ODS_RESEARCH_PROJECT</option></select></div><div class="field"><label>分片键</label><select class="select"><option>project_id</option></select></div><div class="field"><label>并发线程</label><input class="input" value="8"></div><div class="field"><label>单批数量</label><input class="input" value="10,000"></div><div class="field"><label>限速</label><input class="input" value="50,000 条/秒"></div></div><div class="notice" style="margin-top:18px">建议在23:00-06:00执行，预估时长 3.8 小时。</div><div class="drawer-foot"><button class="btn" data-action="capacity">预估容量</button><button class="btn primary" data-save>创建任务</button></div>`],
 syncDetail:['同步任务详情',`<div class="kpi-line"><span>已同步</span><strong>5.58亿 / 8.2亿</strong></div><div class="kpi-line"><span>成功分片</span><strong>218 / 320</strong></div><div class="kpi-line"><span>当前水位</span><strong class="mono">ID 558,421,900</strong></div><div class="kpi-line"><span>预计完成</span><strong>16:48</strong></div><h3>最近事件</h3><div class="timeline"><div class="timeline-item"><strong>分片218完成</strong><span class="muted">10:44:18 · 2,560,000条</span></div><div class="timeline-item"><strong>分片217重试成功</strong><span class="muted">10:41:06 · 第2次重试</span></div></div>`],
 dedup:['防重策略',`<div class="form-grid"><div class="field full"><label>默认去重方式</label><select class="select"><option>消息ID + 业务主键</option></select></div><div class="field"><label>去重窗口</label><input class="input" value="24小时"></div><div class="field"><label>Bloom Filter容量</label><input class="input" value="1亿"></div><div class="field"><label>误判率上限</label><input class="input" value="0.01%"></div><div class="field"><label>降级策略</label><select class="select"><option>使用业务主键</option></select></div></div><div class="drawer-foot"><button class="btn primary" data-save>保存策略</button></div>`],
 cursor:['增量游标详情',`<div class="notice">当前游标已持久化，可安全从此位置恢复。</div><div class="kpi-line"><span>当前位点</span><strong class="mono">mysql-bin.018742:894221</strong></div><div class="kpi-line"><span>最后成功消息</span><strong class="mono">MSG-882940118</strong></div><div class="kpi-line"><span>本周重复拦截</span><strong>3,842</strong></div><div class="drawer-foot"><button class="btn danger" data-action="reset">重置游标</button><button class="btn primary" data-action="recover">从此位置恢复</button></div>`],
 dict:['新建业务字典',`<div class="form-grid"><div class="field full"><label>字典名称</label><input class="input" value="科技成果类型"></div><div class="field"><label>字典编码</label><input class="input" value="TECH_ACHIEVEMENT_TYPE"></div><div class="field"><label>数据来源</label><select class="select"><option>科技成果系统</option></select></div><div class="field"><label>同步方式</label><select class="select"><option>定时全量</option></select></div><div class="field"><label>执行周期</label><select class="select"><option>每日 01:00</option></select></div></div><div class="drawer-foot"><button class="btn primary" data-save>创建字典</button></div>`],
 dictDiff:['字典差异审核',`<div class="notice">源系统与中台字典存在3项差异。</div><div class="kpi-line"><span><strong>C39 计算机、通信和其他电子设备制造业</strong><br><small class="muted">名称修改</small></span><input type="checkbox" checked></div><div class="kpi-line"><span><strong>M74 专业技术服务业</strong><br><small class="muted">新增项</small></span><input type="checkbox" checked></div><div class="kpi-line"><span><strong>I64 互联网和相关服务</strong><br><small class="muted">状态变更</small></span><input type="checkbox" checked></div><div class="drawer-foot"><button class="btn" data-close>稍后处理</button><button class="btn primary" data-save>审核通过并同步</button></div>`],
 node:['接入节点详情',`<div class="notice">节点连接正常，最近5分钟平均延迟 62ms。</div><div class="kpi-line"><span>心跳时间</span><strong>刚刚</strong></div><div class="kpi-line"><span>可用性</span><strong>99.98%</strong></div><div class="kpi-line"><span>传输速率</span><strong>12,420条/秒</strong></div><div class="kpi-line"><span>错误率</span><strong>0.02%</strong></div><h3>健康检查</h3><div class="timeline"><div class="timeline-item"><strong>接口连通正常</strong><span class="muted">10:44:20</span></div><div class="timeline-item"><strong>Kafka生产正常</strong><span class="muted">10:44:18</span></div></div>`]
};



function openDrawer(key){
  const data=drawerContent[key]||['功能详情','<div class="empty">详情内容</div>'];
  document.getElementById('drawerTitle').textContent=data[0];
  document.getElementById('drawerBody').innerHTML=data[1];
  document.getElementById('drawer').classList.add('show');
}
function closeDrawer(){document.getElementById('drawer').classList.remove('show')}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}

document.addEventListener('click',e=>{
  const d=e.target.closest('[data-drawer]'); if(d){openDrawer(d.dataset.drawer);return}
  if(e.target.closest('[data-close]')){closeDrawer();return}
  if(e.target.id==='drawer'){closeDrawer();return}
  const toggle=e.target.closest('.toggle'); if(toggle){toggle.classList.toggle('on');toast(toggle.classList.contains('on')?'策略已启用':'策略已停用');return}
  if(e.target.closest('[data-save]')){closeDrawer();toast('保存成功，配置已生效');return}
  const a=e.target.closest('[data-action]'); if(!a)return;
  const messages={refresh:'数据已刷新',filter:'已按条件筛选',test:'连接测试成功，延迟 42ms',retry:'已提交重试任务',publish:'配置已下发',rollback:'已回滚至上一可用版本',scan:'扫描已完成，发现1项新变更',export:'报告已生成',pause:'任务已暂停',resumeTask:'任务已继续执行',recover:'已从最后游标恢复任务',checkAll:'健康检查完成：15个正常，1个需处理',syncDict:'字典同步任务已启动',capacity:'容量评估完成，预计耗时3.8小时',repair:'补数任务已创建',reset:'游标重置需要二次确认',tableMode:'已切换为列表视图',ignore:'变更已标记为忽略'};
  toast(messages[a.dataset.action]||'操作已完成');
});
