import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require=createRequire('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')
const {chromium}=require('playwright')
const browser=await chromium.launch({channel:'msedge',headless:true})
const page=await browser.newPage({viewport:{width:1600,height:1000}})
const errors=[],external=[]
page.on('pageerror',e=>errors.push(e.message))
page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith('http://127.0.0.1:5174/'))external.push(r.url())})
try{
 await page.goto('http://127.0.0.1:5174/?view=reading')
 await page.locator('.review-point-open').filter({has:page.locator('b',{hasText:'F20.1'})}).click()
 await page.locator('.knowledge-node').first().waitFor({timeout:30000})
 assert.deepEqual(await page.locator('.knowledge-tabs [role=tab]').allTextContents(),['知识图谱','技术','学术理论','学者'])
 assert.equal(await page.locator('.knowledge-node').count(),10)
 await page.screenshot({path:'tests/knowledge-graph.png'})
 await page.getByRole('button',{name:'查看套筒单极子',exact:true}).click()
 assert.match(await page.locator('.knowledge-detail').innerText(),/原文证据/)
 await page.getByRole('tab',{name:'技术',exact:true}).click()
 assert.equal(await page.locator('.knowledge-results > button').count(),3)
 await page.getByRole('textbox',{name:'搜索论文关联知识'}).fill('shared-aperture')
 assert.ok(await page.locator('.knowledge-results > button').count()>0)
 await page.getByRole('textbox',{name:'搜索论文关联知识'}).fill('不存在的术语')
 assert.ok(await page.locator('.knowledge-empty').isVisible())
 assert.equal(await page.locator('.knowledge-detail').count(),0)
 await page.getByRole('button',{name:'清除知识搜索'}).click()
 await page.getByRole('tab',{name:'学术理论',exact:true}).click()
 assert.equal(await page.locator('.knowledge-results > button').count(),3)
 await page.screenshot({path:'tests/knowledge-theories.png'})
 await page.getByRole('tab',{name:'学者',exact:true}).click()
 assert.equal(await page.locator('.knowledge-results > button').count(),4)
 await page.getByRole('textbox',{name:'搜索论文关联知识'}).fill('Yihong')
 assert.equal(await page.locator('.knowledge-results > button').count(),1)
 await page.locator('.antenna-page canvas').first().waitFor({timeout:30000})
 await page.locator('.knowledge-detail .knowledge-source').first().click()
 await page.locator('.antenna-focus').waitFor()
 await page.getByRole('button',{name:'清除知识搜索'}).click()
 await page.setViewportSize({width:1100,height:974})
 await page.getByRole('tab',{name:'知识图谱',exact:true}).click()
 await page.screenshot({path:'tests/knowledge-narrow.png'})
 assert.deepEqual(errors,[])
 assert.deepEqual(external,[],'knowledge extraction must not call external AI or data services')
 console.log('Four tabs, 10 source-derived entities, evidence, search, empty states, source navigation and no external requests passed.')
}finally{await browser.close()}
