import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
const require = createRequire('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')
const { chromium } = require('playwright')
const browser = await chromium.launch({headless:true,channel:'msedge'})
const context = await browser.newContext({viewport:{width:1600,height:1000}})
const page = await context.newPage()
const errors=[]
page.on('pageerror', error=>errors.push(error.message))
try {
  await page.goto('http://127.0.0.1:5174/?view=reading')
  await page.locator('.review-point-open').first().waitFor({timeout:30000})
  const ids=['F11','F12','F13','F15','F19','F20.1','F5.1','F5.2','F5.3','F6.1','F6.2','F17','F18.3','F6.3','F18.2','F7.1','F7.2','F7.3','F7.4','F7.5','F7.6','F8.1','F20.2','F3.2','F1.1','F1.2','F2.1','F2.2','F3.1','F4','F8.2','F9','F10','F14','F16','F18.1','F20.3','F20.4']
  for (const id of ids) {
    await page.locator('.review-point-open').filter({has:page.locator('b',{hasText:new RegExp('^'+id.replaceAll('.','\\.')+'$')})}).click()
    await page.waitForFunction(()=>['focused','context','failed'].includes(document.querySelector('.prototype-focus-layer')?.dataset.phase),{},{timeout:15000})
    const phase=await page.locator('.prototype-focus-layer').getAttribute('data-phase')
    const feedback=await page.locator('.prototype-focus-feedback').innerText()
    console.log(id,phase,feedback)
    if(phase==='failed'){console.log('errors',errors);console.log((await page.locator('body').innerText()).slice(-3000));await page.screenshot({path:'tests/reading-focus-failed.png'})}
    assert.notEqual(phase,'failed',feedback)
    assert.ok(await page.locator('.prototype-focus-frame').count())
  }
  await page.screenshot({path:'tests/reading-focus-desktop.png'})
  await page.getByRole('button',{name:'F10 审核详情',exact:true}).click()
  await page.locator('.review-edit textarea').fill('保留测试备注')
  await page.getByRole('button',{name:'‹ 返回功能列表',exact:true}).click()
  await page.getByRole('dialog',{name:'保存审核修改'}).waitFor()
  await page.getByRole('button',{name:'继续编辑',exact:true}).click()
  assert.equal(await page.locator('.review-edit textarea').inputValue(),'保留测试备注')
  await page.getByRole('button',{name:'‹ 返回功能列表',exact:true}).click()
  await page.getByRole('button',{name:'放弃修改',exact:true}).click()
  const pointButton=id=>page.locator('.review-point-open').filter({has:page.locator('b',{hasText:new RegExp('^'+id.replaceAll('.','\\.')+'$')})})
  await pointButton('F10').click()
  await page.getByRole('button',{name:'新建笔记',exact:true}).click()
  await page.locator('.antenna-note-draft textarea').last().fill('真实草稿保护验证')
  await pointButton('F15').click()
  await page.waitForFunction(()=>document.querySelector('.prototype-focus-layer')?.dataset.phase==='failed')
  assert.equal(await page.locator('.antenna-note-draft textarea').last().inputValue(),'真实草稿保护验证')
  await page.locator('.antenna-note-actions').getByRole('button',{name:'取消',exact:true}).click()
  await page.setViewportSize({width:1100,height:974})
  await pointButton('F11').click()
  await page.waitForFunction(()=>document.querySelector('.prototype-focus-layer')?.dataset.phase==='focused')
  assert.ok((await page.locator('.reading-review').getAttribute('class')).includes('is-collapsed'))
  await page.screenshot({path:'tests/reading-focus-narrow.png'})
  await page.getByRole('button',{name:'展开设计评审',exact:true}).click()
  await pointButton('F5.1').click()
  await page.waitForFunction(()=>document.querySelector('.prototype-focus-layer')?.dataset.phase==='focused')
  assert.equal(await page.locator('.prototype-focus-frame').count(),2)
  const outlineBox=await page.locator('.antenna-outline').boundingBox()
  const paperBox=await page.locator('.antenna-scroll').boundingBox()
  assert.ok(paperBox.x>=outlineBox.x+outlineBox.width-1,'outline must not cover PDF target')
  await page.getByRole('button',{name:'放大',exact:true}).click()
  await page.getByRole('button',{name:'展开设计评审',exact:true}).click()
  await pointButton('F5.1').click()
  await page.waitForFunction(()=>document.querySelector('.prototype-focus-layer')?.dataset.phase==='focused')
  await page.getByRole('button',{name:'展开设计评审',exact:true}).click()
  await page.getByRole('combobox',{name:'评审模式',exact:true}).selectOption('story')
  await page.locator('.review-story-feature').first().click()
  await page.waitForFunction(()=>['focused','context'].includes(document.querySelector('.prototype-focus-layer')?.dataset.phase))
  await page.getByRole('button',{name:'返回文件列表',exact:true}).click()
  await page.locator('.antenna-reader').waitFor({state:'detached'})
  assert.deepEqual(errors,[])
} finally { await browser.close() }
