import {createRequire} from 'node:module'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const require=createRequire('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')
const {chromium}=require('playwright')
const browser=await chromium.launch({channel:'msedge',headless:true})
const report=[];let testPage
try{
 const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[]
 testPage=page;page.on('pageerror',e=>errors.push(String(e)))
 await page.goto('http://127.0.0.1:5174/?view=research')
 await page.getByRole('button',{name:'个人空间',exact:true}).waitFor({timeout:60000})
 await page.getByRole('button',{name:'个人空间',exact:true}).click()
 await page.getByRole('button',{name:'回收站',exact:true}).click()
 await page.getByRole('heading',{name:'个人空间 · 回收站'}).waitFor()
 assert.equal(await page.locator('.sidebar').getByText('回收站',{exact:true}).count(),0)
 assert.equal(await page.locator('th').getByText('删除者',{exact:true}).count(),0)
 report.push('个人空间回收站入口、返回及列范围通过')
 await page.getByRole('button',{name:'返回空间',exact:true}).click()
 const exported=await page.evaluate(async()=>{
  const {exportDocumentDocx,exportTableXlsx}=await import('/src/researchExport.ts')
  const table={documentId:801,columns:[{id:'a',name:'数值',type:'number'},{id:'b',name:'公式',type:'text'}],rows:[{id:'r',values:{a:'2',b:'=A1*3'}}]}
  const doc={id:800,title:'导出验证',kind:'在线文档',richHtml:'<h1>测试标题</h1><p><strong>中文正文</strong><a href="https://example.com">书签</a></p><p><span data-latex="\\frac{1}{2}+x^2"></span></p><table><tbody><tr><td><p>单元格</p></td></tr></tbody></table><p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aFf8AAAAASUVORK5CYII="/></p>'}
  const word=await exportDocumentDocx(doc),sheet=exportTableXlsx(table)
  const bytes=async blob=>Array.from(new Uint8Array(await blob.arrayBuffer()))
  return {word:await bytes(word),sheet:await bytes(sheet)}
 })
 fs.writeFileSync('../outputs/research-v1-20260922/export-check.docx',Buffer.from(exported.word));fs.writeFileSync('../outputs/research-v1-20260922/export-check.xlsx',Buffer.from(exported.sheet))
 const JSZip=require('jszip');const zip=await JSZip.loadAsync(Buffer.from(exported.word)),xml=await zip.file('word/document.xml').async('string')
 assert.match(xml,/中文正文/);assert.match(xml,/<w:tbl>/);assert.match(xml,/<m:f>/);assert.match(xml,/<m:sSup>/);assert.ok(Object.keys(zip.files).some(k=>k.startsWith('word/media/')))
 const mammoth=createRequire(import.meta.url)('mammoth');assert.match((await mammoth.extractRawText({buffer:Buffer.from(exported.word)})).value,/中文正文/)
 const XLSX=createRequire(import.meta.url)('xlsx'),book=XLSX.read(Buffer.from(exported.sheet),{type:'buffer'});assert.equal(book.Sheets['数据'].B2.f,'A2*3');assert.equal(book.Sheets['数据'].B2.v,6)
 report.push('DOCX 中文、图片、表格、书签、分数与上标；XLSX 数值与公式通过')
 const rollback=await page.evaluate(async()=>{
  const {atomicResearchPurge}=await import('/src/researchPurge.ts'),{saveOriginalFile,loadOriginalFile,deleteOriginalFile}=await import('/src/localFiles.ts')
  const pdf=await import('/src/pdfArchive.ts')
  const pdfFile=new File(['%PDF-1.7\nfixture'],'fixture.pdf',{type:'application/pdf'});await pdf.savePdfArchiveFile(998003,pdfFile,await pdfFile.arrayBuffer())
  const note={id:'rollback-note',documentId:998003,kind:'highlight',pageNumber:1,quote:'原文',note:'笔记完整',rects:[{x:.1,y:.1,width:.2,height:.1}],createdAt:'2026-09-22T01:00:00Z',updatedAt:'2026-09-22T01:00:00Z'}
  const saved=await pdf.savePdfAnnotations(998003,[note],[]);if(!saved.ok)throw Error(saved.error)
  await saveOriginalFile(998001,new File(['原件A'],'A.docx'));await saveOriginalFile(998002,new File(['原件B'],'B.docx'))
  localStorage.setItem('intelligent-research-portal:transaction-test','保留')
  localStorage.setItem('gkx-reading-workspace-v1','智能阅读保持')
  let failed=false
  try{await atomicResearchPurge(async()=>{await deleteOriginalFile(998001);await deleteOriginalFile(998002);await pdf.deletePdfArchive(998003);localStorage.removeItem('intelligent-research-portal:transaction-test');throw Error('注入中途失败')})}catch{failed=true}
  const original=await pdf.loadPdfArchiveFile(998003),notes=await pdf.loadPdfAnnotations(998003)
  return {failed,a:await(await loadOriginalFile(998001)).text(),b:await(await loadOriginalFile(998002)).text(),pdf:original.ok?new TextDecoder().decode(original.value.data):null,note:notes.ok?notes.value[0]?.note:null,metadata:localStorage.getItem('intelligent-research-portal:transaction-test'),reading:localStorage.getItem('gkx-reading-workspace-v1')}
 })
 assert.deepEqual(rollback,{failed:true,a:'原件A',b:'原件B',pdf:'%PDF-1.7\nfixture',note:'笔记完整',metadata:'保留',reading:'智能阅读保持'});report.push('整次删除故障回退：两个原件、PDF、笔记及元数据完整，智能阅读不变')
 await page.evaluate(async()=>{
  const {persistResearchDocument,persistRecycledResearchDocument}=await import('/src/documentContent.ts')
  const member=(id,role)=>({id,name:id===1?'张三':'同级管理者',role,initials:'张',color:'#000',status:'在线',joinedAt:'2026-09-22'})
  localStorage.setItem('research:team-spaces:v1',JSON.stringify([{name:'验收管理',description:'',members:[member(1,'管理'),member(2,'管理')]},{name:'验收编辑',description:'',members:[member(1,'编辑')]},{name:'验收查看',description:'',members:[member(1,'查看')]},{name:'非成员团队',description:'',members:[member(2,'管理')]}]))
  const doc=(id,title,location)=>({id,title,location,owner:'原创建者',createdAt:'2026-09-22 09:00',visitedAt:'2026-09-22 10:00',updatedAt:'2026-09-22 09:00',size:'1 KB',kind:'在线文档',favorite:true,owned:false,shared:true,spaceScope:'team',content:'验收内容',richHtml:'<p>验收内容</p>'})
  for(const d of [doc(9911,'待改名','验收编辑'),doc(9912,'只读文档','验收查看'),doc(9913,'隐藏文档','非成员团队')])persistResearchDocument(d)
  for(const d of [doc(9914,'异地恢复','验收查看/旧目录'),doc(9915,'管理回收资料','验收管理'),doc(9916,'编辑回收资料','验收编辑')])persistRecycledResearchDocument({...d,deletedAt:'2026-09-22 10:00',deletedBy:'真实删除者'})
 })
 await page.reload();await page.getByRole('button',{name:'团队空间',exact:true}).click();await page.getByRole('button',{name:'验收查看',exact:true}).click()
 assert.equal(await page.getByRole('button',{name:'非成员团队',exact:true}).count(),0)
 const viewRow=page.locator('tr').filter({hasText:'只读文档'})
 assert.equal(await viewRow.getByRole('button',{name:'分享',exact:true}).isDisabled(),true)
 await viewRow.getByRole('button',{name:'只读文档更多操作'}).click()
 assert.equal(await page.getByRole('menuitem',{name:'重命名'}).isDisabled(),true)
 assert.equal(await page.getByRole('menuitem',{name:'删除',exact:true}).isDisabled(),true)
 await page.keyboard.press('Escape')
 await viewRow.getByRole('button',{name:'编辑“只读文档”'}).click()
 assert.equal(await page.getByRole('textbox',{name:'文档正文'}).getAttribute('contenteditable'),'false')
 await page.getByRole('button',{name:'返回',exact:true}).click()
 await page.getByRole('button',{name:'回收站',exact:true}).click()
 assert.equal(await page.locator('th').getByText('删除者',{exact:true}).count(),1)
 assert.equal(await page.getByText('真实删除者',{exact:true}).count(),1)
 assert.equal(await page.getByText('管理回收资料',{exact:true}).count(),0)
 assert.equal(await page.getByRole('button',{name:'彻底删除',exact:true}).isDisabled(),true)
 const handle=async dialog=>{if(dialog.type()==='prompt')await dialog.accept('验收编辑');else await dialog.accept()};page.on('dialog',handle)
 await page.getByRole('button',{name:'恢复',exact:true}).click()
 await page.getByText('回收站为空',{exact:true}).waitFor()
 page.off('dialog',handle)
 const restored=await page.evaluate(async()=>{const {loadResearchDocuments}=await import('/src/documentContent.ts');const {loadFolders}=await import('/src/folderContent.ts');return {doc:loadResearchDocuments([]).find(d=>d.id===9914),folders:loadFolders('team',[])}})
 assert.equal(restored.doc.location,'验收编辑/旧目录');assert.ok(restored.folders.some(f=>f.location==='验收编辑'&&f.name==='旧目录'))
 report.push('查看者入口及详情只读，跨团队隔离，选可写团队重建目录恢复通过')
 await page.getByRole('button',{name:'验收编辑',exact:true}).click()
 let editRow=page.locator('tr[data-document-id="9911"]')
 await editRow.getByRole('button',{name:'待改名更多操作'}).click();await page.getByRole('menuitem',{name:'重命名'}).click();await page.getByLabel('文档新名称').fill('改名成功');await editRow.getByRole('button',{name:'保存',exact:true}).click()
 editRow=page.locator('tr').filter({hasText:'改名成功'});await editRow.getByRole('button',{name:'改名成功更多操作'}).click();await page.getByRole('menuitem',{name:'删除',exact:true}).click();await page.getByRole('dialog',{name:'移入回收站',exact:true}).getByRole('button',{name:'移入回收站',exact:true}).click()
 await page.getByRole('button',{name:'回收站',exact:true}).click()
 assert.equal(await page.locator('tr').filter({hasText:'改名成功'}).getByText('张三',{exact:true}).count(),1)
 const purgeRow=page.locator('tr').filter({hasText:'改名成功'});page.once('dialog',d=>d.accept());await purgeRow.getByRole('button',{name:'彻底删除'}).click();await purgeRow.waitFor({state:'detached'})
 report.push('编辑者重命名、删除者记录、彻底删除通过')
 await page.getByRole('button',{name:'验收管理',exact:true}).click();await page.getByRole('button',{name:/空间管理/}).click();await page.getByRole('tab',{name:'成员管理'}).click()
 assert.equal(await page.getByLabel('同级管理者操作权限').isDisabled(),true)
 await page.getByRole('button',{name:'取消',exact:true}).click()
 report.push('同级管理权限不可降级通过')
 await page.evaluate(()=>localStorage.setItem('research:portal-identity:v1',JSON.stringify({id:1,institutionId:'demo-institution',role:'管理员'})))
 await page.reload();await page.getByRole('button',{name:'团队空间',exact:true}).click()
 await page.getByRole('button',{name:'非成员团队',exact:true}).click()
 await page.getByRole('button',{name:/空间管理/}).click();await page.getByRole('tab',{name:'成员管理'}).click()
 assert.equal(await page.getByLabel('同级管理者操作权限').isDisabled(),false)
 await page.getByRole('button',{name:'取消',exact:true}).click()
 report.push('机构管理员可管理本机构非成员团队及普通管理者权限通过')
 await page.getByRole('button',{name:'验收编辑',exact:true}).click()
 await page.evaluate(async(word)=>{
  const docs=await import('/src/documentContent.ts'),tables=await import('/src/dataTableContent.ts'),files=await import('/src/localFiles.ts')
  const base=docs.loadResearchDocuments([]).find(d=>d.id===9914)
  docs.persistResearchDocument({...base,id:9917,title:'原件改名展示',kind:'Word文档',originalFileName:'原始.docx'})
  await files.saveOriginalFile(9917,new File([new Uint8Array(word)],'原始.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}))
  docs.persistResearchDocument({...base,id:9918,title:'表格',kind:'数据表格'})
  const table=tables.createBlankResearchDataTable(9918,'blank','张三','2026-09-22 12:00');tables.persistResearchDataTable(table)
 },exported.word)
 await page.reload();await page.getByRole('button',{name:'团队空间',exact:true}).click();await page.getByRole('button',{name:'验收编辑',exact:true}).click()
 const folderRow=page.locator('tr').filter({hasText:'旧目录'})
 await folderRow.getByRole('button',{name:'旧目录更多操作'}).click();page.once('dialog',d=>d.accept('改名目录'))
 // Space folders use an inline rename form, while workbench folders use a prompt.
 page.removeAllListeners('dialog');await page.getByRole('menuitem',{name:'重命名',exact:true}).click()
 await page.getByLabel('文件夹新名称').fill('改名目录');await page.getByLabel('文件夹新名称').press('Enter')
 const movedPath=await page.evaluate(async()=>{const docs=await import('/src/documentContent.ts');return docs.loadResearchDocuments([]).find(d=>d.id===9914)?.location})
 assert.equal(movedPath,'验收编辑/改名目录')
 const downloadPromise=page.waitForEvent('download');await page.locator('tr').filter({hasText:'改名目录'}).getByRole('button',{name:'下载',exact:true}).click();const download=await downloadPromise
 const zipPath='../outputs/research-v1-20260922/folder-check.zip';await download.saveAs(zipPath)
 const folderZip=await JSZip.loadAsync(fs.readFileSync(zipPath))
 assert.ok(folderZip.file('改名目录/异地恢复.docx'));assert.ok(folderZip.file('改名目录/表格.xlsx'))
 assert.deepEqual(await folderZip.file('改名目录/原始.docx').async('nodebuffer'),Buffer.from(exported.word))
 report.push('文件夹改名同步子路径；ZIP 保留层级、真实 DOCX/XLSX 和上传原件通过')
 await page.screenshot({path:'../outputs/research-v1-20260922/personal-space.png',fullPage:true})
 assert.deepEqual(errors,[])
 console.log(report.join('\n'))
 fs.writeFileSync('../outputs/research-v1-20260922/browser-results.json',JSON.stringify({report,errors},null,2))
}catch(error){if(testPage){console.log(await testPage.locator('main').first().getAttribute('data-annotation-context'));console.log(await testPage.locator('.app-shell').getAttribute('inert'));console.log((await testPage.locator('body').innerText()).slice(-2500));await testPage.screenshot({path:'../outputs/research-v1-20260922/failure.png'})}throw error}finally{await browser.close()}
