const {chromium}=require('C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')
const assert=require('node:assert/strict')
;(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true})
 try{
  const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.goto('http://127.0.0.1:5174/?view=research&review=prd')
  await page.getByLabel('PRD功能区域').selectOption('workbench')
  assert.ok(await page.locator('.prd-feature').count()>12)
  await page.locator('.prd-feature-heading').first().click()
  await page.getByRole('button',{name:'R2.2 → 合规详情',exact:true}).click()
  await page.getByRole('button',{name:/REQ-W1-01.*→/}).click()
  assert.equal(await page.getByLabel('评审模式',{exact:true}).inputValue(),'prd')
  await page.getByRole('button',{name:'编辑需求与关联',exact:true}).click()
  await page.getByLabel('功能名称',{exact:true}).fill('最近浏览列表字段 · 修订测试')
  await page.getByLabel('功能优先级',{exact:true}).selectOption('P2')
  await page.getByLabel('本次修改说明').fill('调整优先级并补充字段说明')
  await page.getByRole('button',{name:'保存小修改'}).click()
  let book=await page.evaluate(()=>JSON.parse(localStorage.getItem('research-prd-book-v2')))
  assert.equal(book.revisions[1].changes.length,1)
  assert.equal(book.revisions[1].changes[0].before.priority,'P0')
  assert.equal(book.revisions[1].changes[0].after.priority,'P2')
  await page.getByRole('button',{name:'版本与改动记录'}).click()
  await page.getByText('本版本小修改 · 1',{exact:true}).waitFor()
  await page.getByRole('button',{name:'创建大版本',exact:true}).click()
  await page.getByLabel('新版本名称').fill('v3.0 测试版本')
  await page.getByLabel('版本规划',{exact:true}).fill('下一版本的验证规划')
  await page.getByRole('button',{name:'创建并设为当前版本'}).click()
  book=await page.evaluate(()=>JSON.parse(localStorage.getItem('research-prd-book-v2')))
  assert.equal(book.revisions.length,3)
  await page.getByRole('button',{name:'返回需求'}).click()
  await page.getByRole('button',{name:'新增功能点',exact:true}).click()
  await page.getByLabel('功能名称',{exact:true}).fill('新增删除验证功能')
  await page.getByLabel('流程与交互规则',{exact:true}).fill('点击确认后保存；失败保留原输入。')
  await page.getByLabel('本次修改说明').fill('新增测试功能')
  await page.getByRole('button',{name:'保存小修改'}).click()
  await page.getByRole('button',{name:/REQ-CUSTOM.*新增删除验证功能/}).click()
  page.once('dialog',d=>d.accept('测试完成，删除该功能'))
  await page.getByRole('button',{name:'删除功能点',exact:true}).last().click()
  book=await page.evaluate(()=>JSON.parse(localStorage.getItem('research-prd-book-v2')))
  const added=book.revisions.at(-1).changes
  assert.equal(added.length,2);assert.ok(!added[0].before&&added[0].after);assert.ok(added[1].before&&!added[1].after)
  assert.equal(book.revisions[1].changes.length,1)
  await page.getByLabel('PRD功能区域').selectOption('personal')
  await page.getByRole('button',{name:/^REQ-P2-02 /}).click()
  await page.getByRole('button',{name:'新建在线文档',exact:true}).click()
  await page.locator('.prototype-focus-layer[data-phase="focused"]').waitFor()
  await page.getByRole('button',{name:'手动框选 / 校正',exact:true}).click()
  await page.getByRole('button',{name:'载入AI框选'}).click()
  assert.ok(await page.locator('.manual-focus-editor li').count()>0)
  await page.getByLabel('框选1width').fill('90')
  await page.getByRole('button',{name:'保存并定位'}).click()
  await page.locator('.prototype-focus-layer[data-phase="focused"]').waitFor()
  assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('research-prd-manual-regions-v1'))['REQ-P2-02'].regions[0].width===.9))
  await page.reload()
  assert.ok((await page.getByLabel('PRD版本').locator('option').allTextContents()).some(s=>s.includes('v3.0')))
  await page.getByLabel('PRD功能区域').selectOption('workbench')
  await page.locator('.prd-feature-heading').first().click()
  assert.match(await page.locator('.prd-feature-heading').first().innerText(),/修订测试/)
  await page.screenshot({path:'.local/prd-v2-desktop.png'})
  await page.setViewportSize({width:390,height:844})
  const side=page.locator('.research-review')
  if((await side.getAttribute('class')).includes('is-collapsed'))await page.getByRole('button',{name:'展开合规评审'}).click()
  assert.ok((await side.boundingBox()).width<=390)
  await page.screenshot({path:'.local/prd-v2-mobile.png'})
  assert.deepEqual(errors,[])
  console.log('PASS: granular PRD, priority edit, bidirectional links, history, major version, focus, manual correction persistence, desktop/mobile')
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)})
