import {useRef,useState} from 'react'
import {Modal} from './Modal'
import {validateUploadBatch} from '../uploadPolicy'
type Entry={file:File;status:string;done:boolean}
export function BatchUploadDialog({onClose,onUpload,findConflicts,destination}:{onClose:()=>void;onUpload:(file:File)=>Promise<void>;findConflicts:(files:File[])=>string[];destination:string}){
 const [entries,setEntries]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[finished,setFinished]=useState(false);const folderInput=useRef<HTMLInputElement>(null),stop=useRef(false),running=useRef(false)
 const addFiles=(files:FileList|null)=>{if(!files)return;const all=[...(finished?[]:entries),...Array.from(files).map(file=>({file,status:'待上传',done:false}))];try{validateUploadBatch(all.map(e=>e.file));setEntries(all);setError('');setFinished(false)}catch(e){setError(String(e))}}
 const run=async()=>{if(running.current||finished)return;running.current=true;setBusy(true);stop.current=false;setError('');try{const files=entries.map(e=>e.file);validateUploadBatch(files);const names=findConflicts(files);if(names.length){setError('以下文件重名，请修改名称后重新选择：'+names.join('、'));return}for(let i=0;i<entries.length;i++){if(stop.current)break;setEntries(v=>v.map((e,j)=>j===i?{...e,status:'正在上传…'}:e));try{await onUpload(entries[i].file);setEntries(v=>v.map((e,j)=>j===i?{...e,status:'上传成功',done:true}:e))}catch(err){setEntries(v=>v.map((e,j)=>j===i?{...e,status:'失败：'+String(err)}:e));setError('上传已停止，已成功文件保留；未完成文件请重新选择上传。');break}}setFinished(true)}catch(e){setError(String(e))}finally{running.current=false;setBusy(false)}}
 const close=()=>{if(busy){if(window.confirm('仍有文件未完成上传。停止后续上传？当前文件处理完成后停止，已成功文件保留。'))stop.current=true;return}onClose()}
 return <Modal title="批量上传文件" auditTarget="research-import" onClose={close} onSubmit={e=>{e.preventDefault();void run()}} confirmText={busy?'正在上传…':'上传'} confirmDisabled={busy||finished||!entries.length} cancelText="关闭"><p>支持 Word（.doc、.docx）、Excel（.xls、.xlsx）、PDF；可选择文件或文件夹并保留目录层级。每批最多 20 个文件，单文件最大 50 MB。</p><p>保存位置：{destination}。同目录同类型同名时，请修改名称后上传。</p><div className="upload-pickers"><label className="button button--secondary">选择文件<input type="file" multiple accept=".doc,.docx,.xls,.xlsx,.pdf" disabled={busy} onChange={e=>{addFiles(e.target.files);e.target.value=''}}/></label><button className="button button--secondary" type="button" disabled={busy} onClick={()=>folderInput.current?.click()}>选择文件夹</button><input hidden type="file" multiple ref={el=>{folderInput.current=el;el?.setAttribute('webkitdirectory','')}} onChange={e=>{addFiles(e.target.files);e.target.value=''}}/></div>{error&&<p role="alert">{error}</p>}<div className="batch-upload-list">{entries.map((e,i)=><div key={i}><span>{e.file.webkitRelativePath||e.file.name}</span><span>{e.status}</span>{!e.done&&!finished&&<button type="button" disabled={busy} onClick={()=>{setEntries(v=>v.filter((_,j)=>j!==i));setError('')}}>移除</button>}</div>)}</div></Modal>
}
