import { PdfArchiveReader } from './PdfArchiveReader'
import { loadReadingFile, downloadReadingFile } from '../readingFiles'
import { exportPdfNotes } from '../pdfArchive'
import type { ReadingDocument, ReadingNote } from '../readingData'
import type { ResearchDocument, PdfArchiveAnnotation } from '../types'
export function ReadingUploadedPdf({document:doc,notes,onNotesChange,onBack,onLanguageChange}:{document:ReadingDocument;notes:ReadingNote[];onNotesChange:(notes:ReadingNote[])=>boolean;onBack:()=>void;onLanguageChange:(language:'zh'|'en')=>void}){
 const item:ResearchDocument={id:doc.id,title:doc.title,language:doc.language,location:doc.folder,owner:'当前用户',createdAt:'',visitedAt:'',size:doc.size,kind:'PDF文档',favorite:doc.favorite,owned:true,shared:false};
 const annotations:PdfArchiveAnnotation[]=notes.map(n=>n.pdfAnnotation?{...n.pdfAnnotation,id:String(n.id),documentId:doc.id}:({id:String(n.id),documentId:doc.id,kind:n.imageDataUrls?.length?'screenshot':'highlight',pageNumber:n.sourceAnchor?.page??1,quote:n.title,note:n.excerpt,rects:n.sourceRects??[],imageDataUrl:n.imageDataUrls?.[0],createdAt:n.createdAt,updatedAt:n.createdAt}));
 return <PdfArchiveReader onLanguageChange={onLanguageChange} document={item} onClose={onBack} storage={{loadFile:async()=>{try{const f=await loadReadingFile(doc.id);return{ok:true,value:{documentId:doc.id,name:f.name,type:f.type,size:f.size,data:await f.arrayBuffer(),updatedAt:''}}}catch(e){return{ok:false,error:String(e)}}},loadAnnotations:async()=>({ok:true,value:annotations}),loadImage:async()=>({ok:false,error:'阅读图片仅来自当前阅读笔记，不读取科研存储'})}} onSaveAnnotations={async(next)=>{const values=next.map((a,i)=>({pdfAnnotation:{...a,id:String(Number.isSafeInteger(Number(a.id))&&Number(a.id)>0?Number(a.id):Date.now()+i)},id:Number.isSafeInteger(Number(a.id))&&Number(a.id)>0?Number(a.id):Date.now()+i,title:a.quote||'截图笔记',excerpt:a.note||a.quote||'截图笔记',createdAt:a.createdAt,color:'#FFE4BA',sourceAnchor:{page:a.pageNumber,x:a.rects[0]?.x??0,y:a.rects[0]?.y??0},sourceRects:a.rects,imageDataUrls:a.imageDataUrl?[a.imageDataUrl]:undefined}));if(!onNotesChange(values))return{ok:false,error:'笔记保存失败，原内容保留'};return{ok:true,annotations:next.map((a,i)=>({...a,id:String(values[i].id)}))}}} onDownload={async()=>{try{await downloadReadingFile(doc.id);return{ok:true}}catch(e){return{ok:false,error:String(e)}}}} onExport={a=>exportPdfNotes(item,a)}/>
}
