import {useState} from 'react'
import {createPortal} from 'react-dom'
import {Modal} from './Modal'
import {loadReviewSeed,reviewKey,withReviewLock} from '../reviewTransport'
import type {Product} from '../productStorage'
const keys=(p:Product)=>[reviewKey(p,'prd'),reviewKey(p,'annotations'),`prototype-annotations-${p}-v1`,`${p}-compliance-names-v1`,p==='research'?'research-compliance-review-v1':'reading-design-review-v1',p==='research'?'research-prd-manual-regions-v1':'reading-compliance-manual-v1',...(p==='research'?['research-prd-book-v2']:[])]
const capture=(p:Product)=>Object.fromEntries(keys(p).map(k=>[k,localStorage.getItem(k)]))
export function ReviewDemoControls({product}:{product:Product}){
 const [open,setOpen]=useState(false),[backup,setBackup]=useState<Record<string,string|null>|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 if(!import.meta.env.PROD)return null
 return <><button type="button" className="demo-data-control" onClick={()=>{setOpen(true);setBackup(null);setConfirmed(false);setError('')}}>更新评审示例</button>{open&&createPortal(<Modal title="备份与更新评审示例" onClose={()=>{if(!busy)setOpen(false)}} confirmText="更新当前产品评审示例" confirmDisabled={!backup||!confirmed||busy} onSubmit={async e=>{e.preventDefault();if(!backup||!confirmed||busy)return;setBusy(true);setError('');try{const [prd,annotations]=await Promise.all([loadReviewSeed(product,'prd'),loadReviewSeed(product,'annotations')]);await withReviewLock(product,async()=>{if(JSON.stringify(capture(product))!==JSON.stringify(backup))throw Error('备份后内容已变化，请重新备份');try{for(const key of keys(product))localStorage.removeItem(key);const oldPrd=JSON.parse(backup[reviewKey(product,'prd')]||'null'),oldAnnotations=JSON.parse(backup[reviewKey(product,'annotations')]||'null');prd.revision=Math.max(prd.revision,oldPrd?.revision||0)+1;annotations.revision=Math.max(annotations.revision,oldAnnotations?.revision||0)+1;localStorage.setItem(reviewKey(product,'prd'),JSON.stringify(prd));localStorage.setItem(reviewKey(product,'annotations'),JSON.stringify(annotations))}catch(e){for(const [key,value] of Object.entries(backup))if(value===null)localStorage.removeItem(key);else localStorage.setItem(key,value);throw e}});location.reload()}catch(e){setError(String(e));setBusy(false)}}}><p>仅替换当前产品的 PRD、注释、合规修改和框选校正。文件、笔记、表格及另一产品的数据保留。请先保存编辑内容；其他窗口的旧稿保存会提示冲突。</p><button type="button" disabled={busy} onClick={()=>{try{const data=capture(product),url=URL.createObjectURL(new Blob([JSON.stringify({format:'gkx-review-backup-v1',product,createdAt:new Date().toISOString(),storage:data},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=product+'-评审备份-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);setBackup(data);setConfirmed(false)}catch(e){setError(String(e))}}}>下载当前评审备份</button>{backup&&<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已确认下载完成，同意替换上述评审内容</label>}{error&&<p role="alert">{error}</p>}</Modal>,document.body)}</>
}
