import {useMemo,useState} from 'react'
import {Modal} from './Modal'
import {prepareTableImport,type TableImportFile} from '../tableImport'
import {parseDelimitedData} from '../dataTableContent'
import {displayMinute} from '../displayFormat'
import type {ResearchDataTable} from '../types'
export function TableImportDialog({table,user,onClose,onImport}:{table:ResearchDataTable;user:string;onClose:()=>void;onImport:(table:ResearchDataTable)=>void}){
 const [files,setFiles]=useState<TableImportFile[]>([]),[mode,setMode]=useState<'append'|'replace'>('append'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const validation=useMemo(()=>{if(!files.length)return '';try{prepareTableImport(table,files,mode,user,displayMinute(new Date().toISOString()));return ''}catch(e){return String(e)}},[files,mode,table,user]);
 return <Modal title="导入表格数据" wide onClose={onClose} confirmText="确认导入" confirmDisabled={busy||!files.length||!!validation||!!error} onSubmit={e=>{e.preventDefault();if(busy||validation||error)return;try{const next=prepareTableImport(table,files,mode,user,displayMinute(new Date().toISOString()));if(mode==='replace'&&!window.confirm('将替换当前表格全部记录，保留字段设置。确认替换？'))return;onImport(next);onClose()}catch(e){setError(String(e))}}}><p>支持 CSV / TSV，每个文件不超过 2 MiB、500 行、30 字段。首行为字段名称，须与当前表格字段对应。</p><input aria-label="选择数据文件" type="file" multiple accept=".csv,.tsv" disabled={busy} onChange={async e=>{const selected=Array.from(e.target.files??[]);setBusy(true);setError('');try{if(selected.some(f=>f.size>2*1024*1024))throw Error('单文件不能超过 2 MiB');setFiles(await Promise.all(selected.map(async f=>({name:f.name,size:f.size,text:await f.text()}))))}catch(e){setFiles([]);setError(String(e))}finally{setBusy(false)}}}/><label className="field-label">导入方式<select aria-label="导入方式" className="text-field" value={mode} onChange={e=>{setMode(e.target.value as 'append'|'replace');setError('')}}><option value="append">追加记录</option><option value="replace">替换全部记录</option></select></label>{(error||validation)&&<p role="alert">{error||validation}</p>}{files.map((file,index)=>{const result=parseDelimitedData(file.text,/\.tsv$/i.test(file.name)?'\t':',');return <section key={index}><h3>{file.name}</h3>{!result.ok?<p role="alert">{result.error}</p>:<><p>{result.rows.length} 条记录，{result.headers.length} 个字段；下方预览前 5 条。</p><div style={{overflow:'auto'}}><table className="document-table"><thead><tr>{result.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{result.rows.slice(0,5).map((row,r)=><tr key={r}>{row.map((cell,c)=><td key={c}>{cell}</td>)}</tr>)}</tbody></table></div></>}</section>})}</Modal>
}
