import type {
  CommentItem,
  FolderItem,
  MemberItem,
  ResearchDocument,
  ResearchNote,
  TodoItem,
} from './types'

export const initialDocuments: ResearchDocument[] = [
  {
    id: 1,
    title: '深度学习报告',
    location: '我的空间/研究',
    owner: '张三',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '1.3 MB',
    kind: '在线文档',
    favorite: false,
    owned: true,
    shared: false,
    description: '汇总卷积神经网络、注意力机制与科研数据分类实验，对不同模型的准确率和训练效率进行比较。',
    keywords: ['深度学习', '注意力机制', '模型训练', '科研数据'],
    content: '实验采用统一的数据集划分和随机种子，对卷积网络与注意力模型进行对照。结果显示，小样本条件下注意力机制提升了分类准确率，但训练稳定性仍需通过消融实验进一步验证。',
  },
  {
    id: 2,
    title: '科研项目进度表',
    location: 'AI研究团队/管理',
    owner: '李四',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '2.3 MB',
    kind: '在线文档',
    favorite: true,
    owned: true,
    shared: true,
    description: '记录 AI 研究团队的阶段目标、实验排期、负责人以及风险跟踪情况。',
    keywords: ['项目管理', '里程碑', '实验排期', 'AI研究团队'],
    content: '本阶段完成数据清洗和基线模型复现，下一里程碑为特征工程与模型调优。样本标注数量不足被列为主要风险项，需要明确补充数据的来源、负责人和完成时间。',
  },
  {
    id: 3,
    title: '项目需求文档',
    location: '产品研发部/产品',
    owner: '王五',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '16 MB',
    kind: 'PDF文档',
    favorite: false,
    owned: true,
    shared: false,
    description: '面向科研协作平台整理用户需求、核心流程、权限模型和交付验收标准。',
    keywords: ['产品需求', '权限', '协作', '验收标准'],
    content: '平台需要支持科研资料集中管理、团队协作和跨内容检索。用户可搜索文档信息和笔记正文，搜索结果必须标明来源，并在权限校验后提供定位操作。',
  },
  {
    id: 4,
    title: '实验数据分析',
    location: '产品研发部/产品',
    owner: '王五',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '856 KB',
    kind: 'Word文档',
    favorite: false,
    owned: false,
    shared: true,
    description: '整理电化学实验数据，包含异常值处理、统计检验与关键指标对比。',
    keywords: ['实验数据', '异常值', '统计分析', '电化学'],
    content: '循环测试数据按温度、倍率和材料批次分组。异常值使用四分位距方法标记，不直接删除原始记录，并同时输出处理前后的统计指标作为对照。',
  },
  {
    id: 5,
    title: '技术架构设计',
    location: '产品研发部/产品',
    owner: '王五',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '4.6 MB',
    kind: 'Excel文档',
    favorite: false,
    owned: false,
    shared: true,
    description: '说明科研门户的前端、服务层、检索索引和权限模块之间的技术关系。',
    keywords: ['技术架构', '检索索引', '权限模块', '服务层'],
    content: '系统采用分层架构，前端负责交互与状态反馈，服务层统一编排空间、文档与笔记数据。检索请求先执行权限过滤，再进行相关性排序和高亮摘要生成。',
  },
  {
    id: 6,
    title: '文献综述整理',
    location: '产品研发部/产品',
    owner: '王五',
    createdAt: '2026-04-15 10:30',
    visitedAt: '2026-04-15 10:30',
    size: '5.0 MB',
    kind: 'Excel文档',
    favorite: false,
    owned: false,
    shared: true,
    description: '围绕储能材料与锂硫电池方向归纳代表性研究、方法演进和待解决问题。',
    keywords: ['文献综述', '储能材料', '锂硫电池', '研究现状'],
    content: '现有研究主要通过多孔碳载体、极性吸附位点和催化界面抑制多硫化物穿梭效应。后续需要比较不同材料体系在高硫载量条件下的循环稳定性。',
  },
  {
    id: 7,
    title: '科研项目数据与进度表',
    location: '我的空间/研究项目',
    owner: '张研究员',
    createdAt: '2026-08-18 09:30',
    visitedAt: '2026-08-24 16:45',
    size: '18 KB',
    kind: '数据表格',
    favorite: true,
    owned: true,
    shared: true,
    description: '集中跟踪储能材料项目的实验任务、负责人、项目进度、截止日期与数据文件。',
    keywords: ['数据表格', '项目进度', '科研数据', '多人协作', '文件上传'],
    content: '储能材料项目进度、实验数据和阶段成果汇总。文献语义检索模型复现由张三负责，医学知识图谱实体标注由李四负责，实验组样本质量核验由王五负责，消融实验与误差分析由赵敏负责，基线数据清洗与去重已完成，阶段成果评审材料整理进行中。数据文件包括 retrieval-evaluation.csv、entity-annotation.xlsx、sample-qc.csv、baseline-clean-v3.csv 与 review-materials.xlsx；原始数据、分析结果与任务责任人可在表格视图和表单视图中统一管理。',
  },
  {
    id: 9,
    title: '固态电解质材料实验数据表',
    location: '科研数据管理/材料实验',
    owner: '周岚',
    createdAt: '2026-07-28 09:10',
    visitedAt: '2026-08-26 09:00',
    size: '5.2 MB',
    kind: '数据表格',
    favorite: false,
    owned: true,
    shared: true,
    description: '集中管理固态电解质实验批次、材料体系、烧结温度、电导率、测试进度与原始数据文件。',
    keywords: ['材料实验', '固态电解质', '实验批次', '离子电导率', '数据表格'],
    content: 'Li₆PS₅Cl、LLZO、LATP 与 LGPS 等固态电解质材料的实验批次、性能测试、数据复核、负责人和数据文件汇总。',
  },
  {
    id: 10,
    title: '多中心临床与调研项目总表',
    location: '科研数据管理/临床调研',
    owner: '李医生',
    createdAt: '2026-07-15 08:30',
    visitedAt: '2026-08-26 09:10',
    size: '7.5 MB',
    kind: '数据表格',
    favorite: false,
    owned: true,
    shared: true,
    description: '统一监控多中心队列与调研项目的样本纳入、阶段状态、负责人、截止时间和数据文件。',
    keywords: ['临床队列', '调研项目', '多中心', '样本进度', '数据表格'],
    content: '社区高血压、糖尿病随访、睡眠质量、屏幕使用、慢阻肺依从性和基层医务人员 AI 使用等项目的跨中心进度与数据文件。',
  },
]

export const initialResearchNotes: ResearchNote[] = [
  {
    id: 1,
    documentId: 1,
    title: '模型训练结论',
    content: '注意力机制在小样本科研数据上的准确率提升明显，但需要继续观察过拟合和训练稳定性。下一轮补充消融实验，并统一随机种子。',
    createdAt: '2026-04-16 09:20',
    updatedAt: '2026-05-06 14:35',
    tags: ['模型训练', '实验结论'],
  },
  {
    id: 2,
    documentId: 2,
    title: '本周里程碑复盘',
    content: '数据清洗已完成，特征工程进度达到 80%。风险项是标注样本不足，需要在周三前确认新增数据来源和负责人。',
    createdAt: '2026-04-18 16:10',
    updatedAt: '2026-05-05 11:08',
    tags: ['里程碑', '风险跟踪'],
  },
  {
    id: 3,
    documentId: 3,
    title: '需求评审重点',
    content: '全文搜索需要同时覆盖文档信息与用户笔记，搜索结果应标明来源，并支持从结果返回所在空间。个人设置需保留未保存提醒。',
    createdAt: '2026-04-20 13:40',
    updatedAt: '2026-05-04 17:22',
    tags: ['需求评审', '全文搜索'],
  },
  {
    id: 4,
    documentId: 4,
    title: '异常数据处理记录',
    content: '第 7 组循环测试存在温度漂移，暂不删除原始数据。采用四分位距标记异常值，并在统计结果中保留处理前后对照。',
    createdAt: '2026-04-22 10:05',
    updatedAt: '2026-05-03 09:45',
    tags: ['实验数据', '异常值'],
  },
  {
    id: 5,
    documentId: 5,
    title: '架构选型记录',
    content: '检索索引与业务数据分层维护，权限过滤必须先于结果排序。前端只保存查询历史，不缓存无权限的文档摘要。',
    createdAt: '2026-04-24 15:18',
    updatedAt: '2026-05-02 18:30',
    tags: ['技术架构', '检索索引'],
  },
]

export const initialFolders: FolderItem[] = [
  { id: 1, name: '研究项目', count: 15, updatedAt: '2026-04-30 14:20' },
  { id: 2, name: '实验数据', count: 8, updatedAt: '2026-04-30 14:20' },
  { id: 3, name: '研究项目', count: 15, updatedAt: '2026-04-30 14:20' },
]

export const initialTodos: TodoItem[] = [
  { id: 1, title: '完成储能材料综述第三章初稿', due: '2024-06-28', level: 'danger', done: false },
  { id: 2, title: '审阅李助理的实验数据整理报告', due: '2024-06-27', level: 'warning', done: false },
  { id: 3, title: '更新锂硫电池专利数据库', due: '2024-06-25', level: 'warning', done: false },
  { id: 4, title: '准备7月研讨会演讲PPT', due: '2024-07-05', level: 'muted', done: false },
]

export const initialComments: CommentItem[] = [
  { id: 1, author: '李助理', content: '第3章的实验参数表格需要补充原料来源信息', time: '2小时前', attachment: '储能材料专利分析报告_v3.pdf' },
  { id: 2, author: '陈博士', content: '图5的坐标轴标注有误，建议修正', time: '昨天', attachment: '锂硫电池实验数据集.xlsx' },
  { id: 3, author: '王分析师', content: '政策汇编已更新至2024年6月最新版本', time: '2天前', attachment: '深圳未来产业政策汇编.pdf' },
]

export const initialMembers: MemberItem[] = [
  { id: 1, name: '张研究员', role: '管理员', initials: '张', color: '#5b8ff9', status: '在线', joinedAt: '2025-12-05' },
  { id: 2, name: '李助理', role: '编辑者', initials: '李', color: '#7c3aed', status: '在线', joinedAt: '2025-12-05' },
  { id: 3, name: '陈博士', role: '编辑者', initials: '陈', color: '#0891b2', status: '离线', joinedAt: '2025-12-02' },
  { id: 4, name: '王分析师', role: '查看员', initials: '王', color: '#f97316', status: '在线', joinedAt: '2025-12-01' },
  { id: 5, name: '刘研究员', role: '查看员', initials: '刘', color: '#14b8a6', status: '离线', joinedAt: '2025-12-01' },
]

export const teamNames = ['AI研究团队', '产品研发部', '数据分析组', '技术架构组', '实验室管理']
