import { ownsStorageKey, productDatabases, snapshotMarker, type Product } from './productStorage'
type Value = any
const req = <T,>(r: IDBRequest<T>) => new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})
const done = (tx: IDBTransaction) => new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})
async function encode(v: Value): Promise<Value> {
 if(v instanceof Blob || v instanceof ArrayBuffer){const bytes=new Uint8Array(v instanceof Blob?await v.arrayBuffer():v);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {__backup:v instanceof File?'File':v instanceof Blob?'Blob':'ArrayBuffer',data:btoa(binary),type:v instanceof Blob?v.type:undefined,name:v instanceof File?v.name:undefined,lastModified:v instanceof File?v.lastModified:undefined}}
 if(Array.isArray(v))return Promise.all(v.map(encode));if(v&&typeof v==='object')return Object.fromEntries(await Promise.all(Object.entries(v).map(async([k,x])=>[k,await encode(x)])));return v
}
async function decode(v: Value): Promise<Value> {
 if(v?.__backup){const bytes=Uint8Array.from(atob(v.data),c=>c.charCodeAt(0));return v.__backup==='File'?new File([bytes],v.name,{type:v.type,lastModified:v.lastModified}):v.__backup==='Blob'?new Blob([bytes],{type:v.type}):bytes.buffer}
 if(Array.isArray(v))return Promise.all(v.map(decode));if(v&&typeof v==='object')return Object.fromEntries(await Promise.all(Object.entries(v).map(async([k,x])=>[k,await decode(x)])));return v
}
export async function captureProduct(product: Product) {
 const local:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i)!;if(ownsStorageKey(product,key)||key===snapshotMarker(product))local[key]=localStorage.getItem(key)!}
 const available=await indexedDB.databases(),databases:Value[]=[];
 for(const name of productDatabases[product]){if(!available.some(d=>d.name===name))continue;const db=await req(indexedDB.open(name));try{const stores=[];for(const name of Array.from(db.objectStoreNames)){const tx=db.transaction(name),st=tx.objectStore(name);const [keys,values]=await Promise.all([req(st.getAllKeys()),req(st.getAll())]);stores.push({name,keyPath:st.keyPath,autoIncrement:st.autoIncrement,indexes:Array.from(st.indexNames).map(n=>{const ix=st.index(n);return{name:n,keyPath:ix.keyPath,unique:ix.unique,multiEntry:ix.multiEntry}}),records:await Promise.all(values.map(async(value,i)=>({key:keys[i],value:await encode(value)})))})}databases.push({name,version:db.version,stores})}finally{db.close()}}
 return {format:'gkx-product-backup-v1',product,createdAt:new Date().toISOString(),local:Object.fromEntries(Object.entries(local).sort(([a],[b])=>a.localeCompare(b))),databases}
}
export async function prepareLatestDemo(product: Product) {
 const response=await fetch(import.meta.env.BASE_URL+'demo/manifest.json');if(!response.ok)throw Error('演示快照不可用，当前资料未改变');const manifest=await response.json();const local=Object.fromEntries(Object.entries(manifest.local).filter(([key])=>ownsStorageKey(product,key))) as Record<string,string>;
 for(const value of Object.values(local))JSON.parse(value);
 async function materialize(v:Value):Promise<Value>{if(v?.__kind&&v.path){if(!/^demo\/files\/[\w.-]+$/.test(v.path))throw Error('附件路径不合法');const r=await fetch(import.meta.env.BASE_URL+v.path);if(!r.ok)throw Error('演示附件下载失败');const data=await r.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==v.sha256)throw Error('附件校验失败');return v.__kind==='File'?new File([data],v.name,{type:v.type,lastModified:v.lastModified}):v.__kind==='Blob'?new Blob([data],{type:v.type}):data}if(Array.isArray(v))return Promise.all(v.map(materialize));if(v&&typeof v==='object')return Object.fromEntries(await Promise.all(Object.entries(v).map(async([k,x])=>[k,await materialize(x)])));return v}
 const databases=[];for(const db of manifest.databases.filter((d:Value)=>productDatabases[product].includes(d.name))){databases.push({...db,stores:await Promise.all(db.stores.map(async(s:Value)=>({...s,records:await Promise.all(s.records.map(async(r:Value)=>({...r,value:await materialize(r.value)})))})))})}
 return {product,local:{...local,[snapshotMarker(product)]:manifest.version},databases}
}
export async function applyProduct(snapshot:Value, encoded=false){const product=snapshot.product as Product;const available=await indexedDB.databases();for(const name of productDatabases[product]){const info=snapshot.databases.find((d:Value)=>d.name===name);if(!info&&!available.some(d=>d.name===name))continue;const open=indexedDB.open(name,info?.version);open.onupgradeneeded=()=>{for(const s of info?.stores??[]){const st=open.result.createObjectStore(s.name,{keyPath:s.keyPath,autoIncrement:s.autoIncrement});for(const ix of s.indexes)st.createIndex(ix.name,ix.keyPath,{unique:ix.unique,multiEntry:ix.multiEntry})}};const db=await req(open);try{const prepared=await Promise.all((info?.stores??[]).map(async(s:Value)=>({...s,records:await Promise.all(s.records.map(async(r:Value)=>({...r,value:encoded?await decode(r.value):r.value})))})));const names=Array.from(db.objectStoreNames);if(names.length){const tx=db.transaction(names,'readwrite'),finished=done(tx);for(const name of names)tx.objectStore(name).clear();for(const s of prepared){const st=tx.objectStore(s.name);for(const r of s.records){if(st.keyPath)st.put(r.value);else st.put(r.value,r.key)}}await finished}}finally{db.close()}}
 for(const key of Object.keys(localStorage))if(ownsStorageKey(product,key)||key===snapshotMarker(product))localStorage.removeItem(key);for(const [key,value]of Object.entries(snapshot.local))if(ownsStorageKey(product,key)||key===snapshotMarker(product))localStorage.setItem(key,value as string)
}
export async function resetProduct(product:Product, backup:Awaited<ReturnType<typeof captureProduct>>, prepared:Awaited<ReturnType<typeof prepareLatestDemo>>){if(backup.product!==product||prepared.product!==product)throw Error('资料产品不匹配');const current=await captureProduct(product);if(JSON.stringify({...current,createdAt:''})!==JSON.stringify({...backup,createdAt:''}))throw Error('资料在备份后已变化，请重新备份');try{await applyProduct(prepared)}catch(error){try{await applyProduct(backup,true)}catch{throw Error('重置与回滚未完成，请保留已下载备份并停止编辑')}throw error}}
export async function initializeFreshProduct(product:Product){for(const key of Object.keys(localStorage))if(ownsStorageKey(product,key)||key===snapshotMarker(product))return;const backup=await captureProduct(product);if(backup.databases.some(d=>d.stores.some((s:Value)=>s.records.length)))return;await resetProduct(product,backup,await prepareLatestDemo(product))}
