import {sessionStorage} from '../storage.ts'
import {displayMinute} from '../displayFormat.ts'
import {PrdFilterControls,PrdExportButton,ReviewBottomTools} from '../researchReview/PrdPresentation.tsx'
import {matchesPrdFilters,prdDisplayNumbers} from '../researchReview/prdDisplay.ts'
import {useEffect,useRef,useState,type ReactNode} from 'react'
import {PrdPanel} from '../researchReview/PrdPanel.tsx'
import {PrdEditor} from '../researchReview/PrdEditor.tsx'
import {comparePrd,reviseFeature} from '../researchReview/prdStore.ts'
import type {PrdFeature} from '../researchReview/prd.ts'
import {readingOverview} from './catalog.ts'
import {points} from './model.ts'
import {readingLocations} from '../prototypeFocus/readingTargets.ts'
import {installReadingMappings} from '../prototypeFocus/manual.ts'
import {ReadingManualEditor} from './ReadingManualEditor.tsx'
import {downloadReading,readingMarkdown,type ReadingBook} from './prdBook.ts'
import '../researchReview/review.css'
import './prd.css'
function rememberedView(){try{const v=JSON.parse(sessionStorage.getItem('reading-prd-view-v1')||'null');return v&&typeof v.chapter==='string'&&Array.isArray(v.opened)&&v.opened.every((x:unknown)=>typeof x==='string')?v:{chapter:'overview',opened:[]}}catch{return {chapter:'overview',opened:[]}}}

export function ReadingDifference({before,after}:{before?:PrdFeature;after?:PrdFeature}){
 const text=(f?:PrdFeature)=>f?[`${f.id} ${f.title}`,`${f.priority} · ${f.release}`,`着重讲解：${f.emphasis?'是':'否'}；设计进度：${f.designProgress??'待讨论'}`,...(f.rules??[]).map(g=>`${g.title}\n${g.items.map((s,i)=>`${i+1}. ${s}`).join('\n')}`),`合规：${f.compliance?.join('、')||'无'}`,`原型：${f.links.map(l=>l.id).join('、')}`,`人工框选：${f.manual?JSON.stringify(f.manual):'系统建议'}`].join('\n\n'):'（无）'
 return <div className="prd-difference"><section><h4>修改前</h4><pre>{text(before)}</pre><h4>修改后</h4><pre>{text(after)}</pre></section></div>
}
export function ReadingPrdWorkspace({book,revisionNumber,save,query,clearQuery,opened,onOpened,onCompliance,onLocate,annotationTools}:{annotationTools?:(feature:PrdFeature)=>ReactNode;book:ReadingBook;revisionNumber:number;save:(b:ReadingBook,expected:number)=>Promise<boolean>;query:string;clearQuery:()=>void;opened:string|null;onOpened:()=>void;onCompliance:(id:string)=>void;onLocate:(id:string,label:string)=>void}){
 const [version,setVersion]=useState(()=>{try{return sessionStorage.getItem('reading-prd-version-v1')||'current'}catch{return 'current'}}),[view,setView]=useState<{chapter:string;opened:string[]}>(rememberedView),[filter,setFilter]=useState({priority:'',emphasis:'',progress:''}),[history,setHistory]=useState(false),[compare,setCompare]=useState(book.current)
 useEffect(()=>{try{sessionStorage.setItem('reading-prd-version-v1',version)}catch{}},[version])
 useEffect(()=>{try{sessionStorage.setItem('reading-prd-view-v1',JSON.stringify(view))}catch{}},[view])
 const [editing,setEditing]=useState<{area:string;feature:PrdFeature;before?:PrdFeature;baseline:number;book:ReadingBook}|null>(null),[boxing,setBoxing]=useState<{feature:PrdFeature;area:string;baseline:number;book:ReadingBook}|null>(null)
 const [creating,setCreating]=useState<{baseline:number;book:ReadingBook}|null>(null),[name,setName]=useState(''),[plan,setPlan]=useState(''),[error,setError]=useState('')
 const revision=book.revisions.find(r=>r.id===(version==='current'?book.current:version))??book.revisions.find(r=>r.id===book.current)!,editable=revision.id===book.current
 useEffect(()=>{if(!opened)return;const v=book.revisions.find(r=>r.id===book.current)!,area=v.areas.find(a=>a.features.some(f=>f.id===opened));if(area){setVersion(v.id);setHistory(false);clearQuery();setFilter({priority:'',emphasis:'',progress:''});setView({chapter:area.id,opened:[opened]})}onOpened()},[opened])
 useEffect(()=>{installReadingMappings(Object.fromEntries(revision.areas.flatMap(a=>a.features).filter(f=>f.manual).map(f=>[f.id,f.manual!])));return()=>installReadingMappings({})},[revision])
 const areaOf=(id:string)=>revision.areas.find(a=>a.features.some(f=>f.id===id))!.id
 const begin=(f?:PrdFeature)=>setEditing({area:f?areaOf(f.id):view.chapter,feature:f??{id:`READ-CUSTOM-${crypto.randomUUID().slice(0,8)}`,title:'',priority:'P1',release:revision.name,purpose:'',behavior:'',contract:'',current:'',acceptance:[],rules:[{title:'',items:['']}],links:[],compliance:[]},before:f,baseline:revisionNumber,book:structuredClone(book)})
 const exportVersion=()=>downloadReading(`智能阅读-PRD-${revision.name}.md`,readingMarkdown(revision.areas,revision.name,revision.plan))
 const [quickBusy,setQuickBusy]=useState(false)
 const quickLock=useRef(false)
 const quickUpdate=async(f:PrdFeature,patch:Partial<PrdFeature>)=>{if(quickLock.current||!editable)return;quickLock.current=true;setQuickBusy(true);try{const area=revision.areas.find(a=>a.features.some(x=>x.id===f.id))!.id;const next=reviseFeature(book,area,f,{...f,...patch},'卡片快捷修改');if(!await save(next as ReadingBook,revisionNumber))setError('修改未保存，请重试；其他窗口可能已更新数据。');else setError('')}catch{setError('保存失败，请重试。')}finally{quickLock.current=false;setQuickBusy(false)}}
 return <div className="prd-panel reading-prd-workspace">
 <ReviewBottomTools product="reading" slot="version"><div className="prd-bottom-controls"><label>版本<select aria-label="PRD版本" value={revision.id} onChange={e=>{setVersion(e.target.value);setView({chapter:'overview',opened:[]})}}>{book.revisions.map(v=><option key={v.id} value={v.id}>{v.name}{v.id===book.current?' · 当前':''}</option>)}</select></label></div></ReviewBottomTools><ReviewBottomTools product="reading"><div className="prd-bottom-actions">
 <PrdExportButton count={readingMarkdown(revision.areas,revision.name,revision.plan).replace(/\s/g,'').length} onClick={exportVersion}/><div className="prd-toolbar"><button onClick={()=>setHistory(!history)}>{history?'返回需求':'版本与改动记录'}</button><button onClick={()=>{setCreating({baseline:revisionNumber,book:structuredClone(book)});setName('');setPlan('')}}>创建大版本</button></div></div></ReviewBottomTools>
 {!view.opened.length&&<PrdFilterControls chapter={view.chapter} areas={revision.areas} query={query} filters={filter} onChange={setFilter}/>}
 {error&&<p className="reading-prd-error" role="alert">{error}</p>}
 {creating&&<form className="prd-version-form" onSubmit={async e=>{e.preventDefault();if(!name.trim()||!plan.trim())return;if(creating.book.revisions.some(v=>v.name===name.trim())){setError('版本名已存在');return}const id=crypto.randomUUID(),next:ReadingBook={...creating.book,current:id,revisions:[...creating.book.revisions,{...structuredClone(revision),id,name:name.trim(),plan:plan.trim(),at:new Date().toISOString(),changes:[]}]};if(await save(next,creating.baseline)){setVersion(id);setCreating(null);setError('')}else setError('创建未保存，名称和规划保留；请核对共享版本后重新创建。')}}><h3>从 {revision.name} 创建大版本</h3><label>版本名称<input aria-label="新版本名称" required value={name} onChange={e=>setName(e.target.value)}/></label><label>版本规划<textarea aria-label="版本规划" required value={plan} onChange={e=>setPlan(e.target.value)}/></label><button type="button" onClick={()=>{if(!name&&!plan||confirm('放弃未保存的版本规划？'))setCreating(null)}}>取消</button><button type="submit">创建并设为当前版本</button></form>}
 {history?<div className="prd-document"><h2>版本与改动记录</h2><p>{revision.plan}</p><small>{displayMinute(revision.at)} · 北京时间</small><button onClick={()=>downloadReading('智能阅读-PRD完整备份.json',JSON.stringify(book,null,2),'application/json')}>导出版本记录</button><label>对比版本<select aria-label="对比版本" value={compare} onChange={e=>setCompare(e.target.value)}>{book.revisions.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><h3>版本差异</h3>{comparePrd(book.revisions.find(v=>v.id===compare)?.areas??[],revision.areas).map(d=><details key={d.id}><summary>{d.id} · {!d.before?'新增':!d.after?'删除':'修改'}</summary><ReadingDifference {...d}/></details>)}<h3>本版本小修改 · {revision.changes.length}</h3>{[...revision.changes].reverse().map(c=><details key={c.id}><summary>{c.after?.title??c.before?.title} · {c.reason}</summary><p>{displayMinute(c.at)} · 北京时间</p><ReadingDifference before={c.before} after={c.after}/></details>)}</div>:<>
 {editable&&!view.opened.length&&view.chapter!=='overview'&&<button className="prd-add" onClick={()=>begin()}>新增功能点</button>}
 <PrdPanel product="智能阅读" overview={readingOverview} source="依据：sidebar.config.ts 中提供的项目需求。" query={query} onClearQuery={()=>{clearQuery();setFilter({priority:'',emphasis:'',progress:''})}} view={view} onViewChange={setView} onLocate={onLocate} catalog={view.opened.length?revision.areas:revision.areas.map(a=>({...a,features:a.features.filter(f=>matchesPrdFilters(f,filter))}))} displayNumbers={prdDisplayNumbers(revision.areas)} filtering={!!(filter.priority||filter.emphasis||filter.progress)} versionLabel={revision.name} extraOverview={<><h3>本版规划</h3><p>{revision.plan}</p><p>P0 核心必需 · P1 重要能力 · P2 体验优化，均可经评审调整。</p></>} headingTools={f=><><button onClick={()=>onLocate(`${f.id}::${f.links[0]?.id??''}`,f.title)}>定位</button>{editable&&<><button onClick={()=>setBoxing({feature:f,area:areaOf(f.id),baseline:revisionNumber,book:structuredClone(book)})}>框选校正</button><button onClick={()=>begin(f)}>编辑</button></>}</>} detailTools={f=>editable?<button onClick={()=>begin(f)}>编辑</button>:<span className="prd-readonly">历史版本 · 只读</span>} cardTools={f=><><label>设计进度<select aria-label={f.title+" 设计进度"} disabled={!editable||quickBusy} data-progress={f.designProgress??"待讨论"} value={f.designProgress??"待讨论"} onChange={e=>void quickUpdate(f,{designProgress:e.target.value as PrdFeature["designProgress"]})}>{["待讨论","待完善","已完成"].map(v=><option key={v}>{v}</option>)}</select></label><label>优先级<select aria-label={f.title+" 优先级"} disabled={!editable||quickBusy} value={f.priority} onChange={e=>void quickUpdate(f,{priority:e.target.value as PrdFeature["priority"]})}>{["P0","P1","P2"].map(v=><option key={v}>{v}</option>)}</select></label><label>着重讲解<select aria-label={f.title+" 着重讲解"} disabled={!editable||quickBusy} value={f.emphasis?"yes":"no"} onChange={e=>void quickUpdate(f,{emphasis:e.target.value==="yes"})}><option value="no">否</option><option value="yes">是</option></select></label></>} featureTools={f=><>{editable&&annotationTools?.(f)}<h4>关联合规项</h4><div className="prd-links">{f.compliance?.length?f.compliance.map(id=><button key={id} onClick={()=>onCompliance(id)}>{id} → 合规详情</button>):<span>未关联合规项</span>}</div><details className="prd-feature-history"><summary>此功能点的修改记录</summary>{revision.changes.filter(c=>c.before?.id===f.id||c.after?.id===f.id).map(c=><div key={c.id}><p>{new Date(c.at).toLocaleString('zh-CN')} · {c.reason}</p><ReadingDifference before={c.before} after={c.after}/></div>)}</details></>}/>
 </>}
 {editing&&<PrdEditor  onDelete={editing.before?async(reason)=>{if(!await save(reviseFeature(editing.book,editing.area,editing.before,undefined,reason||'删除功能点') as ReadingBook,editing.baseline))return false;setView({...view,opened:[]});return true}:undefined} feature={editing.feature} compliancePoints={points} locations={readingLocations} onClose={()=>setEditing(null)} onSave={async(f,reason)=>{if(!f.links.length)throw Error('请至少关联一个真实原型入口。');if(JSON.stringify(f.links)!==JSON.stringify(editing.before?.links))f={...f,manual:undefined};return save(reviseFeature(editing.book,editing.area,editing.before,f,reason) as ReadingBook,editing.baseline)}}/>}
 {boxing&&<ReadingManualEditor feature={boxing.feature} onClose={()=>setBoxing(null)} onSave={(manual,reason)=>save(reviseFeature(boxing.book,boxing.area,boxing.feature,{...boxing.feature,manual},reason) as ReadingBook,boxing.baseline)}/>}
 </div>
}
