import type { PrototypeTarget, PrototypeFocusLocation } from './types'

export const readingTargets: Record<string, PrototypeTarget> = {
  'reading-review':{product:'reading'},
  'reading-library':{product:'reading',readingView:'library'},
  'reading-upload':{product:'reading',readingView:'upload'},
  'reading-tech':{product:'reading',readingView:'antenna-reader',readingRight:'graph',readingKnowledgeTab:'技术'},
  'reading-theory':{product:'reading',readingView:'antenna-reader',readingRight:'graph',readingKnowledgeTab:'学术理论'},
  'reading-scholar':{product:'reading',readingView:'antenna-reader',readingRight:'graph',readingKnowledgeTab:'学者'},
  'reading-reader': { product: 'reading', readingView: 'antenna-reader' },
  'reading-outline': { product: 'reading', readingView: 'antenna-reader', readingLeft: 'outline' },
  'reading-notes': { product: 'reading', readingView: 'antenna-reader', readingRight: 'notes' },
  'reading-figures': { product: 'reading', readingView: 'antenna-reader', readingRight: 'figures' },
  'reading-references': { product: 'reading', readingView: 'antenna-reader', readingRight: 'references' },
  'reading-metadata': { product: 'reading', readingView: 'antenna-reader', readingRight: 'metadata' },
  'reading-graph': { product: 'reading', readingView: 'antenna-reader', readingRight: 'graph' },
  'reading-search': { product: 'reading', readingView: 'antenna-reader', readingTool: 'search' },
}
const target = (navigationTarget: string, selectors: string[], description: string, prerequisite?: string): PrototypeFocusLocation => ({
  navigationTarget, selectors, description, timeoutMs: 6000,
  ...(prerequisite ? { contextOnly: true, prerequisite } : {}),
})
const focus = (id: string) => `[data-focus-id="${id}"]`
const tool = (label: string) => `.antenna-toolbar [aria-label="${label}"]`
export const readingLocations: Record<string, PrototypeFocusLocation> = {
  'READ-library':target('reading-library',['.reading-files-table-scroll'],'文献列表'),
  'READ-library-search':target('reading-library',['.reading-files-search'],'文献搜索'),
  'READ-library-nav':target('reading-library',['.reading-files-nav'],'文献分组'),
  'READ-library-position':target('reading-library',['.reading-files table tbody tr:first-child select'],'文件位置'),
  'READ-library-pages':target('reading-library',['.reading-files-pagination'],'文献分页'),
  'READ-library-actions':target('reading-library',['.reading-file-actions'],'下载与移除'),
  'READ-upload':target('reading-upload',['.reading-upload-page-dropzone'],'文件选择与处理'),
  'READ-upload-folder':target('reading-upload',['.reading-upload-page-folder'],'上传位置'),
  'READ-pdf':target('reading-reader',['.antenna-page[data-paper-page="1"] canvas'],'真实PDF原文'),
  'READ-note-edit':target('reading-notes',['.antenna-new-note'],'笔记编辑入口','请新建或编辑真实笔记；定位不会生成草稿。'),
  'READ-crop-actions':target('reading-reader',[tool('截图笔记')],'截图确认流程入口','请先拖画真实选区，再查看确认、取消与下载。'),
  'READ-figure-note':target('reading-figures',['.antenna-figure:first-of-type footer button:last-child'],'图表笔记联动'),
  'READ-kg-tech':target('reading-tech',['.knowledge-results'],'技术整理'),
  'READ-kg-theory':target('reading-theory',['.knowledge-results'],'学术理论整理'),
  'READ-kg-scholar':target('reading-scholar',['.knowledge-results'],'署名学者整理'),
  'READ-kg-search':target('reading-graph',['.knowledge-search'],'知识检索'),
  'READ-kg-evidence':target('reading-graph',['.knowledge-detail'],'知识原文证据'),
  'READ-review':target('reading-review',['.reading-review .review-top-tools'],'设计评审模式与检索'),
  'READ-review-edit':target('reading-review',['.reading-review .prd-feature-body .prd-toolbar'],'当前功能编辑与关联'),
  'READ-review-version':target('reading-review',['.reading-prd-workspace > .prd-navigation'],'版本与导出'),
  'READ-review-share':target('reading-review',['.reading-prd-status','.reading-review .prd-feature-body .prd-toolbar'],'共享状态与人工框选'),
  'F1.1': target('reading-reader', [tool('摘录选中文字')], '选词翻译入口', '请在原文中选择一个词，查看真实翻译结果。'),
  'F1.2': target('reading-reader', [tool('摘录选中文字')], '选段翻译入口', '请在原文中选择一段文字，查看真实译文。'),
  'F2.1': target('reading-reader', [tool('摘录选中文字')], '文字选区入口', '请拖动选择原文，核对选区与文字是否一致。'),
  'F2.2': target('reading-figures', ['.antenna-figure:first-of-type img'], '提取的图片', '当前展示图表提取结果；独立图片选区交互尚待确认。'),
  'F3.1': target('reading-notes', ['.antenna-new-note'], '摘录笔记入口', '选中文字后可保存摘录；定位不会创建笔记。'),
  'F3.2': target('reading-notes', [focus('reading-source-highlight')], '已保存摘录的原文高亮'),
  'F4': target('reading-reader', [tool('返回上一位置')], '返回上一阅读位置'),
  'F5.1': target('reading-outline', [focus('reading-outline-first'), '.antenna-focus'], '目录条目与原文位置'),
  'F5.2': target('reading-notes', [focus('reading-note-source'), '.antenna-focus'], '笔记与原文位置'),
  'F5.3': target('reading-figures', [focus('reading-figure-source'), '.antenna-focus'], '图表与原图位置'),
  'F6.1': target('reading-references', [focus('reading-reference-marker')], '正文参考文献标记'),
  'F6.2': target('reading-figures', [focus('reading-figure-marker')], '正文图编号标记'),
  'F6.3': target('reading-figures', [focus('reading-table-empty')], '表格标记空状态', '这篇原文没有独立表格，无法验证表标记。'),
  'F7.1': target('reading-reader', [tool('放大')], '放大按钮'),
  'F7.2': target('reading-reader', [tool('缩小')], '缩小按钮'),
  'F7.3': target('reading-reader', ['.antenna-toolbar [aria-label*="全屏"]'], '全屏切换'),
  'F7.4': target('reading-reader', [tool('截图笔记')], '截图工具入口'),
  'F7.5': target('reading-reader', ['.antenna-toolbar [aria-label*="标记"]'], '显示或隐藏标记'),
  'F7.6': target('reading-reader', ['.antenna-page-select input'], '填写页数'),
  'F8.1': target('reading-search', ['.antenna-search-switch', '.antenna-search-panel input'], '全文搜索模式与关键词'),
  'F8.2': target('reading-reader', [tool('摘录选中文字')], '原位短语释义入口', '请先在原文中选择术语，查看对应释义。'),
  'F9': target('reading-notes', ['.antenna-new-note'], '笔记入口', '当前笔记按最新设计已移除标签，不能验证标签功能。'),
  'F10': target('reading-notes', ['.antenna-new-note'], '新建灵感笔记'),
  'F11': target('reading-outline', ['.antenna-left-rail', '.antenna-outline'], '左侧导航与目录'),
  'F12': target('reading-notes', ['.antenna-right-rail', '.antenna-insights > header'], '右侧操作栏与当前面板'),
  'F13': target('reading-references', ['.antenna-reference:first-child'], '解析的参考文献条目'),
  'F14': target('reading-references', [focus('reading-reference-detail')], '引用详情字段', '详情含原型补全字段，请核对各字段来源。'),
  'F15': target('reading-figures', ['.antenna-figure:first-of-type'], '提取的图表及笔记入口'),
  'F16': target('reading-outline', ['.antenna-outline'], '解析的章节层级'),
  'F17': target('reading-references', [focus('reading-reference-marker'), focus('reading-reference-detail')], '引用编号与详情'),
  'F18.1': target('reading-figures', [focus('reading-figure-source'), '.antenna-focus'], '图片与正文关联'),
  'F18.2': target('reading-figures', [focus('reading-table-empty')], '表格关联空状态', '原文没有独立表格，无法验证表与正文关联。'),
  'F18.3': target('reading-references', [focus('reading-reference-source'), '.antenna-focus'], '引用与原文条目'),
  'F19': target('reading-metadata', ['.antenna-metadata'], '论文元数据'),
  'F20.1': target('reading-graph', ['.antenna-graph-scene'], '论文知识图谱'),
  'F20.2': target('reading-search', ['.antenna-search-switch', '.antenna-search-panel input'], '语义搜索模式与关键词'),
  'F20.3': target('reading-metadata', ['.antenna-metadata'], '论文详情信息'),
  'F20.4': target('reading-graph', ['.knowledge-tabs', '.knowledge-panel > .knowledge-scope'], '技术、学术理论、学者分类与归纳数量'),
}
