import type { PrototypeFocusLocation, PrototypeTarget } from './types'

export const researchTargets: Record<string, PrototypeTarget> = {
  'prd-personal-new': {product:'research',section:'personal'},
  'prd-upload': {product:'research',section:'personal',modal:'import-document'},
  'prd-team-new': {product:'research',section:'team',modal:'new-team'},
  'prd-recycle': {product:'research',section:'recycle'},
  'research-workbench': {product:'research',section:'workbench',tab:'recent'},
  'research-quick': {product:'research',section:'workbench',tab:'quick'},
  'research-recent': {product:'research',section:'workbench',tab:'recent'},
  'research-favorites': {product:'research',section:'workbench',tab:'favorites'},
  'research-personal': {product:'research',section:'personal'},
  'research-team': {product:'research',section:'team'},
  'research-members': {product:'research',section:'team',teamTab:'members',surface:'members'},
  'research-invite': {product:'research',section:'team',teamTab:'members',modal:'invite-member'},
  'research-profile': {product:'research',modal:'profile-settings'},
  'research-search': {product:'research',section:'workbench',surface:'search'},
  'research-import': {product:'research',surface:'import'},
  'research-editor': {product:'research',surface:'editor'},
  'research-pdf': {product:'research',surface:'pdf'},
  'research-table': {product:'research',surface:'table'},
}
const focus = (navigationTarget:string, selectors:string[], description:string, options:Partial<PrototypeFocusLocation> = {}):PrototypeFocusLocation => ({navigationTarget,selectors,description,...options})
const recent = (selectors:string[],description:string,options:Partial<PrototypeFocusLocation> = {}) => focus('research-recent',selectors,description,options)
const personal = (selectors:string[],description:string,options:Partial<PrototypeFocusLocation> = {}) => focus('research-personal',selectors,description,options)
const members = (selectors:string[],description:string,options:Partial<PrototypeFocusLocation> = {}) => focus('research-members',selectors,description,options)
const field = (profile:string,column:number) => [`.document-table--${profile} thead th:nth-child(${column})`, `.document-table--${profile} tbody tr:first-child td:nth-child(${column}):not(.empty-cell)`]
const memberMenu = {prerequisite:'需有可管理的成员；定位不更改角色。'}
export const researchLocations: Record<string, PrototypeFocusLocation> = {
  'PRD-RECENT-REMOVE':recent(['.document-table tbody tr:first-child .row-actions > button'],'最近浏览移除记录入口'),
  'PRD-QUICK-LIST':focus('research-quick',['.document-table thead'],'快速访问列表字段'),
  'PRD-QUICK-CANCEL':focus('research-quick',['.document-table tbody tr:first-child .row-actions'],'取消快速访问；无固定内容时请先固定内容'),
  'PRD-QUICK-SORT':focus('research-quick',['.document-table .document-sort'],'快速访问排序控件'),
  'PRD-PIN':personal(['.document-space-menu'],'加入快速访问菜单',{prepare:['reveal:research-document-menu']}),
  'PRD-FAVORITE-CANCEL':focus('research-favorites',['.document-table tbody tr:first-child .row-actions'],'取消收藏入口'),
  'PRD-NEW-FOLDER':personal(['.create-dropdown-menu button:nth-child(1)'],'新建文件夹入口',{prepare:['details:.create-dropdown']}),
  'PRD-NEW-DOC':personal(['.create-dropdown-menu button:nth-child(2)'],'新建在线文档入口',{prepare:['details:.create-dropdown']}),
  'PRD-NEW-TABLE':personal(['.create-dropdown-menu button:nth-child(3)'],'新建在线表格入口',{prepare:['details:.create-dropdown']}),
  'PRD-RENAME':personal(['.document-space-menu'],'重命名所在菜单',{prepare:['reveal:research-document-menu'],contextOnly:true}),
  'PRD-DOWNLOAD':personal(['.document-space-menu'],'下载所在菜单',{prepare:['reveal:research-document-menu'],contextOnly:true}),
  'PRD-ORIGINAL-LOCATION':focus('prd-recycle',['.document-table--recycle thead th:nth-child(5)'],'回收站原位置字段'),
  'PRD-P2':focus('prd-personal-new',['.create-dropdown > summary'],'当前目录的新建入口'),
  'PRD-P3':focus('prd-upload',['.upload-pickers'],'文件与文件夹上传入口；未选择或上传文件'),
  'PRD-T1':focus('prd-team-new',['#team-name'],'团队空间名称；未创建或邀请成员'),
  'PRD-B1':focus('prd-recycle',['.document-table--recycle thead th:nth-child(3)'],'回收站删除时间字段；空列表不生成记录'),
  'PRD-B2':focus('prd-recycle',['.document-table--recycle tbody tr:first-child .row-actions button:first-child, .document-table--recycle:has(.empty-cell) thead th:last-child'],'恢复操作所在位置；空列表仅标示操作列',{contextOnly:true}),
  'PRD-B3':focus('prd-recycle',['.document-table--recycle tbody tr:first-child .danger-link, .document-table--recycle:has(.empty-cell) thead th:last-child'],'彻底删除操作所在位置；空列表仅标示操作列，未执行删除',{contextOnly:true}),
  'R1.1':personal(['.document-table tr:nth-child(1 of [data-document-kind="文件夹"]) [data-focus-id="research-folder-pin"]'],'文件夹快速访问固定/取消入口',{prerequisite:'当前空间需有文件夹。'}),
  'R1.2':focus('research-quick',['.document-table tbody tr[data-document-id^="-"] .document-title-link'],'已固定文件夹的打开入口',{prerequisite:'请先自行固定文件夹；无固定项时不创建示例。'}),
  'R2.1':recent(['.document-table--recent tbody tr:first-child .title-cell'],'最近浏览的第一条文档记录'),
  'R2.2':recent(field('recent',1),'文档名称列与第一条名称'),
  'R2.3':recent(field('recent',4),'文档大小列与第一条大小'),
  'R2.4':recent(field('recent',6),'最后打开时间列与第一条访问时间'),
  'R2.5':recent(field('recent',2),'所属父文件夹列与第一条位置'),
  'R2.6':recent(['.document-table--recent tbody tr:first-child .document-title-link'],'文档详情入口；未代为打开'),
  'R2.7':recent(['.document-table--recent thead th:nth-child(6) .document-sort'],'最近访问排序控件；未更改排序'),
  'R2.8':recent(['.page-size-trigger'],'当前每页条数控件；未更改用户条数选择'),
  'R2.9':recent(['.pagination'],'当前是页码翻页，没有加载更多追加',{contextOnly:true}),
  'R3.1':recent(['.document-space-menu [data-focus-id="research-favorite"]'],'收藏操作入口；未执行收藏',{prepare:['reveal:research-document-menu']}),
  'R3.2':focus('research-favorites',['.document-table--favorites thead','.document-table--favorites tbody tr:first-child'],'收藏列表表头与首条记录或真实空状态'),
  'R3.3':focus('research-favorites',field('favorites',1),'收藏标题'),
  'R3.4':focus('research-favorites',field('favorites',2),'收藏时间'),
  'R3.5':focus('research-favorites',field('favorites',3),'收藏类型标识'),
  'R3.6':focus('research-favorites',field('favorites',4),'收藏大小'),
  'R4.1':personal(['.space-inline-note'],'个人空间说明；本机原型不能证明跨账号私有',{contextOnly:true}),
  'R4.2':personal(field('space',1),'空间内文件及文件夹名称'),
  'R4.3':personal(field('space',2),'文档类型标识'),
  'R4.4':personal(field('space',3),'文档大小'),
  'R4.5':personal(field('space',4),'最后修改时间'),
  'R4.6':personal(field('space',5),'所属父文件夹'),
  'R4.7':personal(field('space',6),'创建者姓名'),
  'R4.8':personal(field('space',7),'创建时间'),
  'R4.9':personal(['.document-table tr[data-document-kind="在线文档"]:not(tr[data-document-kind="在线文档"] ~ tr) .document-title-link'],'在线文档编辑入口；未代为编辑',{prerequisite:'当前列表需有在线文档。'}),
  'R4.10':personal(['.document-space-menu .danger-link'],'文档删除入口；未执行删除',{prepare:['reveal:research-document-menu'],prerequisite:'当前列表需有文档。'}),
  'R5.1':focus('research-team',['.space-toolbar .header-actions'],'团队共同维护入口；多账号同步待验证',{contextOnly:true}),
  'R5.2':members(['.team-management-member:first-child .owner-cell'],'团队成员可见范围；需真实成员账号验证',{contextOnly:true}),
  'R6.1':focus('research-search',['.global-search-input'],'笔记全文搜索输入；请自行输入关键词',{contextOnly:true}),
  'R6.2':focus('research-search',['.global-search-input'],'文档全文搜索输入；请自行输入关键词'),
  'R6.3':focus('research-profile',['#profile-name'],'个人信息姓名设置字段'),
  'R7.1':focus('research-editor',['.continuous-toolbar select','.continuous-toolbar [data-focus-id="editor-粗体"]'],'文本样式与粗体工具'),
  'R7.2':focus('research-editor',['[data-focus-id="editor-无序列表"]','[data-focus-id="editor-有序列表"]'],'列表编辑工具'),
  'R7.3':focus('research-editor',['[data-focus-id="editor-图片"]'],'图片插入入口；未打开文件选择器'),
  'R7.4':focus('research-editor',['[data-focus-id="editor-数学公式"]'],'数学公式入口；未插入内容'),
  'R7.5':focus('research-editor',['[data-focus-id="editor-网页书签"]'],'网页书签入口'),
  'R7.6':focus('research-editor',['[data-focus-id="editor-分割线"]'],'分割线入口；未插入内容'),
  'R7.7':focus('research-editor',['.continuous-paper .tiptap'],'多类型内容正文编辑区'),
  'R8.1':focus('research-import',['.pdf-import-dropzone'],'选择 PDF 文件入口；未上传'),
  'R8.2':focus('research-import',['.pdf-import-dropzone'],'请导入真实 PDF 后查看解析结果',{contextOnly:true}),
  'R8.3':focus('research-pdf',['.pdf-archive-reader__title'],'当前真实存档 PDF 的阅读标题',{timeoutMs:6000}),
  'R8.4':focus('research-pdf',['.pdf-archive-reader__rail'],'划词笔记工具入口；需用户真实选区',{contextOnly:true,timeoutMs:6000}),
  'R8.5':focus('research-pdf',['[data-focus-id="research-pdf-screenshot"]'],'截图笔记入口；未截图',{timeoutMs:6000}),
  'R8.6':focus('research-import',['.pdf-import-dropzone'],'批量选择 PDF 文件入口；未上传'),
  'R8.7':focus('research-pdf',['.pdf-archive-reader__title','.pdf-archive-reader__back'],'存档阅读与返回管理列表入口',{timeoutMs:6000}),
  'R8.8':focus('research-pdf',['[data-focus-id="research-pdf-export"]'],'PDF 笔记导出入口；通用在线笔记导出范围待确认',{contextOnly:true,timeoutMs:6000}),
  'R9.1':focus('research-table',['[data-focus-id="research-table-import"]'],'数据收集导入入口；未导入'),
  'R9.2':focus('research-table',['.data-sheet-save-state'],'数据保存状态；未触发保存'),
  'R9.3':focus('research-table',['.spreadsheet thead'],'项目进度字段；需当前表格包含对应字段',{contextOnly:true}),
  'R9.4':focus('research-table',['[data-focus-id="research-table-import"]'],'上传数据文件入口'),
  'R9.5':focus('research-table',['.data-sheet-share-button'],'多人上传与共享入口；没有多账号服务证据',{contextOnly:true}),
  'R9.6':focus('research-table',['.spreadsheet tbody tr:first-child'],'查看当前表格首条记录'),
  'R9.7':focus('research-table',['.data-sheet-share-button'],'分享权限入口；跨账号访问待验证',{contextOnly:true}),
  'R9.8':focus('research-table',['#data-sheet-tab-table','.spreadsheet thead'],'表格视图与字段'),
  'R9.9':focus('research-table',['#data-sheet-tab-form','.data-sheet-record-details, .data-sheet-form-empty'],'表单视图与当前记录或真实空状态'),
  'R10.1':focus('research-invite',['.candidate-list'],'候选成员列表；未邀请或提交'),
  'R10.2':members(['.team-management-member:first-child .danger-link'],'成员移除入口；未执行移除',memberMenu),
  'R10.3':members(['.team-management-member:first-child select'],'成员角色菜单；未修改角色',memberMenu),
  'R10.4':members(['.team-management-member:first-child .owner-cell'],'空间成员范围；需验证非成员不可访问',{contextOnly:true}),
  'R10.5':focus('research-team',['.space-toolbar .header-actions'],'团队文档维护工具；不同角色权限待验证',{contextOnly:true}),
  'R11.1':members(['.team-management-member:first-child select'],'管理员角色选择器；请自行展开查看选项，未执行设置',memberMenu),
  'R11.2':members(['.team-management-member:first-child select'],'管理员角色选择器；可选择普通角色，未更改角色',memberMenu),
  'R11.3':members(['.team-management-member:first-child select'],'角色管理入口；真实身份鉴权待验证',{contextOnly:true}),
  'R11.4':members(['.team-management-member:first-child select'],'管理员角色入口；最后管理员保护在保存校验时执行，未进行角色变更',{contextOnly:true}),
  'R11.5':members(['.team-management-member:first-child .danger-link'],'移出空间入口；最后管理员保护需实际校验，未执行移除',{...memberMenu,contextOnly:true}),
}
